networkservicemesh/deployments-k8s

alpine.yaml, fake-cross-nse.yaml, namespace.yaml, nsc.yaml, nse.yaml, nsmgr.yaml, proxy-registry-service.yaml, registry-memory.yaml, registry-proxy-dns.yaml, registry-service.yaml, spire/agent-account.yaml, spire/agent-cluster-role.yaml, spire/agent-configmap.yaml, spire/agent-daemonset.yaml, spire/server-account.yaml, spire/server-cluster-role.yaml, spire/server-configmap.yaml, spire/server-service.yaml, spire/server-statefulset.yaml, spire/spire-bundle-configmap.yaml, spire/spire-namespace.yaml, workflows/ci.yaml, workflows/pr-for-updates.yaml
Signed-off-by: Denis Tingajkin <denis.tingajkin@xored.com>
This PR implements a deployment node from  NSM repo pipeline spec.
=> Add initial k8s deployments

README.md, examples/spire/README.md
Signed-off-by: Denis Tingajkin <denis.tingajkin@xored.com>
=> fix: Add missed spire example

apps/nsc-kernel-ponger/ponger.yaml, examples/use-cases/Kernel2Kernel/README.md, examples/use-cases/Kernel2Vxlan2Kernel/README.md, examples/use-cases/Memif2Memif/README.md, examples/use-cases/SriovKernel2Noop/README.md, examples/use-cases/Vfio2Noop/README.md
1. Fixes SR-IOV tests and typos.
2. Removes non-need `NSM_NETWORK_SERVICES` from kernel2kernel NSE patch.
=> Fix SR-IOV tests

examples/use-cases/Vfio2Noop/README.md
VFIO test depends on NSC logs.
Instead of waiting for NSC logs try multiple times to `dpdk_ping`.
=> Fix VFIO test

apps/nsc-memif/nsc.yaml, examples/basic/README.md, examples/use-cases/Kernel2Memif/README.md, examples/use-cases/Kernel2Vxlan2Kernel/README.md, examples/use-cases/Kernel2Vxlan2Memif/README.md, examples/use-cases/Memif2Kernel/README.md, examples/use-cases/Memif2Memif/README.md, examples/use-cases/Memif2Vxlan2Kernel/README.md, examples/use-cases/Memif2Vxlan2Memif/README.md
Closes https://github.com/networkservicemesh/deployments-k8s/issues/312
During testing found the issue: https://github.com/networkservicemesh/cmd-forwarder-vpp/issues/81
=> feat: Cover all variants of connection between nsc, nse via cmd-forwarder-vpp

examples/basic/README.md, examples/features/README.md, examples/features/opa/README.md
=> feat: Move features to separate suite

.github/workflows/ci.yaml
`automerge-action` requires labels to set. 
`merge-me-action ` uses 3 retries by default, so probably we could just increase the attempts count.
=> use merge-me-action with retries instead of automerge-action

.github/workflows/ci.yaml
This PR Fixes: `Pull request created by nsmbot, not dependabot[bot], skipping.`
=> fix: add missed GITHUB_LOGIN for merge-me-action

README.md, examples/use-cases/Kernel2Kernel/README.md, examples/use-cases/Kernel2Memif/README.md, examples/use-cases/Kernel2Vxlan2Kernel/README.md, examples/use-cases/Kernel2Vxlan2Memif/README.md, examples/use-cases/Memif2Kernel/README.md, examples/use-cases/Memif2Memif/README.md, examples/use-cases/Memif2Vxlan2Kernel/README.md, examples/use-cases/Memif2Vxlan2Memif/README.md, examples/use-cases/SriovKernel2Noop/README.md, examples/use-cases/Vfio2Noop/README.md
Previously we've added possible to have bidirectional examples: https://github.com/networkservicemesh/gotestmd/issues/19
Now we can use this to clarify our examples for new people.
=> fix: Add requires sections for use-cases

apps/nsc-kernel/nsc.yaml, apps/nsc-memif/nsc.yaml, apps/nsc-vfio/nsc.yaml, apps/nse-kernel/nse.yaml, apps/nse-memif/nse.yaml, apps/nse-vfio/nse.yaml, examples/features/.gitignore, examples/features/ipv6/Kernel2Kernel/README.md, examples/features/ipv6/Memif2Memif/README.md, examples/features/opa/README.md, examples/multiforwarder/README.md, examples/multiforwarder/kustomization.yaml, examples/use-cases/.gitignore, examples/use-cases/Kernel2Kernel&Vfio2Noop/README.md, examples/use-cases/Kernel2Kernel/README.md, examples/use-cases/Kernel2Memif/README.md, examples/use-cases/Kernel2Vxlan2Kernel&Vfio2Noop/README.md, examples/use-cases/Kernel2Vxlan2Kernel/README.md, examples/use-cases/Kernel2Vxlan2Memif/README.md, examples/use-cases/Memif2Kernel/README.md, examples/use-cases/Memif2Memif/README.md, examples/use-cases/Memif2Vxlan2Kernel/README.md, examples/use-cases/Memif2Vxlan2Memif/README.md, examples/use-cases/SriovKernel2Noop/README.md, examples/use-cases/Vfio2Noop/README.md
Adds examples with both VPP, SR-IOV forwarders running.
Closes #505.
=> Add multi forwarder examples

.github/workflows/ci.yaml
Previously we added with https://github.com/networkservicemesh/integration-tests/pull/285 prefetching.
Now we need to sync up `deployments-k8s` with `integration-tests`
=> fix: deployments-k8s cannot update integration-tests

examples/spire/agent-daemonset.yaml, examples/spire/server-statefulset.yaml
Refers to #727.
Spire before 0.11.1 version have troubles with burstable class (networkservicemesh/networkservicemesh#2183), so we need to update it.
=> Increase spire version

apps/forwarder-sriov/forwarder.yaml, apps/forwarder-vpp/forwarder.yaml, apps/nsc-kernel-ponger/ponger.yaml, apps/nsc-kernel/nsc.yaml, apps/nsc-memif/nsc.yaml, apps/nsc-vfio/nsc.yaml, apps/nse-kernel/nse.yaml, apps/nse-memif/nse.yaml, apps/nse-vfio/nse.yaml, apps/nsmgr/nsmgr.yaml, apps/registry-k8s/registry-k8s.yaml, apps/registry-memory/registry-memory.yaml
Closes #81.
Spire before 0.11.1 version have troubles with burstable class (https://github.com/networkservicemesh/networkservicemesh/issues/2183), so we need to update it.
~Depends on #728.~
~Waiting for #729 to trigger integration tests with updated spire.~
=> Add applications limits

examples/features/webhook/README.md
=> Use postgres container instead of alpine

examples/features/dns/README.md, examples/features/webhook/README.md
Sometimes `mutatingwebhookconfigurations` returns list of webhooks - `nsm-system` and created by default by the cluster (e.g. `aks-webhook-admission-controller` for `AKS` cluster). 
We need only `nsm-system`
=> Getting correct admission-webhook

examples/heal/README.md, examples/heal/local-forwarder-healing/README.md, examples/heal/namespace.yaml, examples/use-cases/LocalForwarderHealing/README.md
Added use case for local forwarder healing in the examples
part of https://github.com/networkservicemesh/deployments-k8s/issues/1174
=> Added local forwarder healing example

examples/interdomain/usecases/Kernel2Vxlan2Kernel/README.md
Makes this https://github.com/networkservicemesh/integration-interdomain-k8s/pull/2 green
=> fix: interdomain tests can fail on ci kind2kind

examples/basic/README.md, examples/use-cases/Kernel2Wireguard2Kernel/README.md, examples/use-cases/Kernel2Wireguard2Memif/README.md, examples/use-cases/Memif2Wireguard2Kernel/README.md, examples/use-cases/Memif2Wireguard2Memif/README.md
Logs from kind cluster:
```
--- PASS: TestRunBasicSuite (757.14s)
--- PASS: TestRunBasicSuite/TestKernel2Kernel (93.10s)
--- PASS: TestRunBasicSuite/TestKernel2Memif (42.42s)
--- PASS: TestRunBasicSuite/TestKernel2Vxlan2Kernel (50.85s)
--- PASS: TestRunBasicSuite/TestKernel2Vxlan2Memif (50.61s)
--- PASS: TestRunBasicSuite/TestKernel2Wireguard2Kernel (55.96s)
--- PASS: TestRunBasicSuite/TestKernel2Wireguard2Memif (50.45s)
--- PASS: TestRunBasicSuite/TestMemif2Kernel (46.30s)
--- PASS: TestRunBasicSuite/TestMemif2Memif (51.83s)
--- PASS: TestRunBasicSuite/TestMemif2Vxlan2Kernel (44.83s)
--- PASS: TestRunBasicSuite/TestMemif2Vxlan2Memif (50.26s)
--- PASS: TestRunBasicSuite/TestMemif2Wireguard2Kernel (50.12s)
--- PASS: TestRunBasicSuite/TestMemif2Wireguard2Memif (49.54s)
PASS
``` …
=> Add wireguard examples

.github/workflows/release.yaml
=> fix: deployments-k8s can not create release branch for integration-tests

examples/use-cases/Kernel2Vxlan2Kernel&Vfio2Noop/README.md
Missed in https://github.com/networkservicemesh/deployments-k8s/pull/2121.
Fixes failing packet tests - https://github.com/networkservicemesh/integration-k8s-packet/pull/100/checks?check_run_id=3110629492.
=> [qfix] Change missed NSE_ prefix to NSM_

examples/heal/remote-nsmgr-death/README.md
Fixes kustomize patches in remote NSMgr death test.
=> [qfix] Fix remote NSMgr death test

examples/features/dns/README.md
Replaces `ping google.com` with `nslookup google.com` because it is not working in github actions.
=> [qfix] Fix DNS test

examples/features/dns/README.md
~Uses `gcr.io/kubernetes-e2e-test-images/dnsutils:1.3` image instead of `alpine` as a client container in DNS tests.~
Installs DNS utils in alpine container in DNS test
=> [qfix] Install DNS utils in alpine container in DNS test

apps/forwarder-vpp/forwarder.yaml
Upgraded VPP consumes more memory, so `400Mi` limit is not enough.
https://github.com/networkservicemesh/cmd-forwarder-vpp/issues/332
=> [qfix] Increase memory limit for VPP applications

examples/interdomain/spire/README.md
Fixes https://github.com/networkservicemesh/integration-interdomain-k8s/pull/57
=> qfix: spire entries have incorrect selectors for 2st and 3d clusters

examples/interdomain/spire/cluster1/kustomization.yaml, examples/interdomain/spire/cluster2/kustomization.yaml, examples/interdomain/spire/cluster3/kustomization.yaml
Makes example working correctly with kubectl 1.19+
Related to https://github.com/kubernetes-sigs/kustomize/pull/1460
=> fix: spire interdomain example is incorrect with new kubernetes clients

README.md, apps/forwarder-host-ovs/forwarder.yaml, apps/forwarder-host-ovs/kustomization.yaml, apps/forwarder-ovs/forwarder.yaml, apps/forwarder-ovs/kustomization.yaml, examples/ovs/README.md, examples/ovs/kustomization.yaml, examples/use-cases/SmartVF2SmartVF/README.md
adds ovs forwarder deployment examples, would help to test [cmd-forwarder-ovs](https://github.com/networkservicemesh/cmd-forwarder-ovs) for which the code development is on going.
Depends on cmd-forwarder-ovs [PR]( https://github.com/networkservicemesh/cmd-forwarder-ovs/pull/7).
Signed-off-by: Periyasamy Palanisamy <periyasamy.palanisamy@est.tech>
=> add ovs forwarder deployment examples

apps/forwarder-vpp/forwarder.yaml
Adds missed mounts to VPP Forwarder deployment.
https://github.com/networkservicemesh/integration-k8s-packet/pull/132
=> [qfix] Add missed mounts to VPP Forwarder deployment

examples/features/jaeger/README.md, examples/features/jaeger/jaeger-patch.yaml, examples/features/jaeger/kustomization.yaml-Memif2Kernel-jaeger
README to explain Jaeger integration and show how to install NSM components with it enabled.  Includes references to how to install Jaeger itself.
forwarder Jaeger functionality depends on the following fixes:
- forwarder-vpp InitJaeger() fix: https://github.com/networkservicemesh/cmd-forwarder-vpp/pull/345
- forwarder dnsPolicy: https://github.com/networkservicemesh/deployments-k8s/pull/2930
=> Add Jaeger example

apps/registry-k8s/crd-ns.yaml, apps/registry-k8s/crd-nse.yaml
`apiextensions.k8s.io/v1beta1` is dropped by v1.22+
=> bump: Update NSM CRD api version to v1

apps/nsc-kernel/nsc.yaml, apps/nsc-vfio/nsc.yaml, apps/nse-kernel/nse.yaml, apps/nsmgr/nsmgr.yaml, apps/registry-k8s/registry-k8s.yaml, apps/registry-memory/registry-memory.yaml, examples/features/nse-composition/README.md
Increases CPU limits for NSM applications. Initial Request for NSE Composition example starts taking less than `10s`.
https://github.com/networkservicemesh/deployments-k8s/issues/3053
=> [deployments-k8s#3053] Increase CPU limits for NSM applications

examples/features/nse-composition/README.md, examples/features/nse-composition/nse-firewall/patch-nse-firewall-vpp.yaml, examples/features/nse-composition/passthrough-1.yaml, examples/features/nse-composition/passthrough-2.yaml, examples/features/nse-composition/passthrough-3.yaml, examples/features/scale-from-zero/pod-template.yaml, examples/use-cases/SmartVF2SmartVF/README.md, examples/use-cases/SriovKernel2Noop/README.md
Reverts networkservicemesh/deployments-k8s#3685
`metadata.labels` not working as supposed
Because of incorrect testing, PR adding labels was merged
Since our main priority now is stability prior to release we reverting it now and return to it later
https://github.com/networkservicemesh/deployments-k8s/issues/3437
=> Revert "Switched to metadata.labels"

apps/nsmgr/nsmgr.yaml
memory: 10Mi is not enough for AKS clusters.
By my local investigation, 25Mi is enough for https://github.com/networkservicemesh/deployments-k8s/blob/main/apps/nsmgr-proxy/nsmgr-proxy.yaml#L74
So  cmd-exclude-prefixes-k8s is a more complex application and it should require more resources.
Potentially closes https://github.com/networkservicemesh/integration-k8s-kind/issues/463
=> qfix: Increase limits for cmd-exclude-prefixes-k8s

examples/use-cases/Kernel2KernelVLAN/README.md
=> qfix: Requires section for 'Test kernel to kernel connection over VLA Trunking at NSE side' is incorrect

apps/admission-webhook-k8s/admission-webhook.yaml, examples/basic/README.md, examples/features/dns/README.md, examples/features/ipv6/Kernel2Kernel/README.md, examples/features/ipv6/Kernel2Wireguard2Kernel/README.md, examples/features/ipv6/Kernel2Wireguard2Memif/README.md, examples/features/nse-composition/README.md, examples/features/webhook/README.md, examples/memory/README.md, examples/memory/kustomization.yaml, examples/use-cases/Kernel2Kernel/README.md, examples/use-cases/Kernel2Memif/README.md, examples/use-cases/Kernel2Vxlan2Kernel/README.md, examples/use-cases/Kernel2Vxlan2Memif/README.md, examples/use-cases/Kernel2Wireguard2Kernel/README.md, examples/use-cases/Kernel2Wireguard2Memif/README.md, external-images.yaml
https://github.com/networkservicemesh/deployments-k8s/issues/2009
=> Added usage of annotations for kernel clients

examples/features/select-forwarder/service.yaml
Closes https://github.com/networkservicemesh/integration-k8s-kind/pull/506
=> qfix: Format of examples/features/select-forwarder/service.yaml is incorrect 

examples/features/select-forwarder/README.md
The example expects to get request logs related to the client in the special forwarder pod. 
Sometimes  NSC and NSE can be started on the same node and a forwarder (to get logs) can be selected from the second node. 
Note: forwarder is daemonset and it deploys on each node.
Don't deploy NSC and NSE on the same node in select-forwarder example.
=> qfix: example select-forwarder is unstable on real clusters

README.md
=> qfix: links for interdomain and floating interdomain examples are incorrect for root README.md

examples/features/select-forwarder/README.md
Fixes
```
time=2021-12-12T20:19:36Z level=info msg=error: a container name must be specified for pod alpine, choose one of: [alpine cmd-nsc coredns] or one of the init containers: [cmd-nsc-init] TestRunFeatureSuite/TestSelect_forwarder=stderr
```
=> qfix: add getting logs from cmd-nsc container for select-forwarder example

examples/interdomain/usecases/FloatingKernel2Wireguard2Kernel/README.md
Fixes problem on CI:
```
time=2021-12-12T23:29:44Z level=info msg=The Deployment "nse-kernel" is invalid: spec.template.spec.containers[0].env[0].valueFrom: Invalid value: "": may not be specified when `value` is not empty TestInterdomainBasicSuite/TestFloatingKernel2Wireguard2Kernel=stderr
time=2021-12-12T23:29:44Z level=info msg=1 TestInterdomainBasicSuite/TestFloatingKernel2Wireguard2Kernel=exitCode
```
=> qfix: remove extra quotes from Floating kernel2wireguard2kernel example

examples/interdomain/usecases/FloatingKernel2Wireguard2Kernel/README.md, examples/interdomain/usecases/FloatingKernel2Wireguard2Kernel/nse.yaml
The current kustomization version in k8s cannot correct override envs. 
For example:
merge of
```
envs:
name: a
value: b
```
and
```
envs:
name: a
valueFrom
....myField.b
```
is not supported in the version of kustomization that using in kubectl
Closes https://github.com/networkservicemesh/deployments-k8s/pull/4056
=> qfix: use direct nse with correct NSM_NAME to avoid problems with kustomize merge

external-images.yaml
CI can fail due to long image pulling => prefersh is using outdated spire.
Real case: https://github.com/networkservicemesh/integration-k8s-kind/runs/4517530239?check_suite_focus=true
```
time=2021-12-14T09:15:13Z level=error msg=command didn't succeed until timeout cmd=kubectl wait -n spire --timeout=1m --for=condition=ready pod -l app=spire-agent
suite.go:130: 
Error Trace:	suite.go:130
suite.gen.go:29
suite.gen.go:23
suite.gen.go:23
suite.go:118
entry_point_test.go:35
Error:      	Not equal: 
expected: 0
actual  : 1
```
=> qfix: Spire external images are outdated

.github/workflows/ci.yaml
closes https://github.com/networkservicemesh/deployments-k8s/issues/4053
=> Add link checker job

examples/features/policy-based-routing/README.md
**Motivation:**
GKE has a different output format:
https://github.com/networkservicemesh/integration-k8s-gke/actions/runs/1744845552
=> [qfix] Fix policy route output format

apps/nse-remote-vlan/kustomization.yaml, apps/nse-remote-vlan/nse-remote-vlan.yaml, examples/remotevlan/README.md, examples/remotevlan/kustomization.yaml, examples/remotevlan/rvlanvpp/README.md, examples/remotevlan/rvlanvpp/device-selector.yaml, examples/remotevlan/rvlanvpp/kustomization.yaml, examples/remotevlan/rvlanvpp/patch-forwarder-vpp.yaml, examples/use-cases/Kernel2RVlan/.gitignore, examples/use-cases/Kernel2RVlan/README.md
=> Add remote vlan mechanism test

examples/features/select-forwarder/README.md, examples/features/select-forwarder/kustomization.yaml, examples/features/select-forwarder/service.yaml
We have a namespace filter to capture logs:
https://github.com/networkservicemesh/integration-tests/blob/main/extensions/logs/logs.go#L235
=> [qfix] Add 'ns-' prefix to select-forwarder to collect logs

apps/nse-remote-vlan/nse-remote-vlan.yaml, examples/remotevlan/README.md, examples/use-cases/Kernel2RVlanBreakout/README.md
Decrease MAX_TOKEN_LIFETIME in NSE to shorten the test run.
Add TRACE level logging to nse_remote_vlan
=> Fix remote vlan example

examples/features/policy-based-routing/README.md
We need to install `iproute2` for `TestPolicyBasedRouting` because of `iprule`.
But as far as we can see, the installation of `iproute2` is unstable and sometimes fails.
https://github.com/networkservicemesh/integration-k8s-kind/runs/5569648874?check_suite_focus=true
This PR adds the use of alpine with the already installed package.
=> [qfix] Use alpine image that already contains iproute2

examples/features/vl3/.gitignore, examples/features/vl3/kustomization.yaml
kustomization.yaml  was missed in examples/features/vl3 due to .gitignore file in [examples/features/.gitignore.](https://github.com/networkservicemesh/deployments-k8s/blob/main/examples/features/.gitignore)
=> qfix: add missed kustomization.yaml for vl3 example

examples/remotevlan/README.md
Skip the ovs forwarder tests temporary 
=> Decrease the scope of rvlanSuite to vpp forwarder only

examples/use-cases/Kernel2Kernel&Vfio2Noop/README.md, examples/use-cases/Kernel2Vxlan2Kernel&Vfio2Noop/README.md, examples/use-cases/Vfio2Noop/README.md
Vfio tests redirects streams in tests - `stdout` stream is never used.
Our bash utility uses channels to receive messages. Since we have nothing there, it just freezes on `stdout` receiving.
https://github.com/networkservicemesh/gotestmd/blob/main/pkg/bash/bash.go#L179
Issue: https://github.com/networkservicemesh/integration-k8s-packet/issues/261
=> Fix streams for vfio tests

examples/spire/README.md
Issue: https://github.com/networkservicemesh/deployments-k8s/issues/5379
Sometimes 1m is not enough for spire-agent - https://github.com/networkservicemesh/integration-k8s-kind/runs/5883097907?check_suite_focus=true
=> Increase spire timeout

apps/forwarder-vpp/forwarder.yaml
Faced on gke cluster
```
kubelet  Liveness probe failed: failed to initialize tls credentials with spiffe. error=context deadline exceeded
```
This PR should fix the problem.
=> fix: forwarder-vpp cpu may not be enough

apps/forwarder-ovs/forwarder.yaml, examples/remotevlan/README.md
Remove cpu resource limit from forwarder app configuration
Re-add ovs-forwarder tests to remote vlan examples
Using debug PRs I was able to find the reason why cmd-forwarder-ovs does not started during integration test run in GihHub. The `kubectl describe pod` command output revealed why the scheduling failed:
```
Warning  FailedScheduling  23s (x4 over 4m)  default-scheduler  0/3 nodes are available: 1 Insufficient cpu, 1 node(s) didn't match Pod's node affinity/selector, 1 node(s) had taint {node-role.kubernetes.io/master: }, that the pod didn't tolerate. TestRunRvlanSuiteSingle/Rvlanovs=stdout
```
The kind worker nodes can allocate 2 CPUs:
```
time=2022-04-13T14:14:25Z level=info msg=kubectl get nodes -o jsonpath='{range …
```
=> Fix ovs examples

examples/k8s_monolith/docker/README.md
We don't need to use static IP for the kind-cluster - if we don't set `NSM_TUNNEL_IP`, it will be resolved automatically by the default route:
https://github.com/networkservicemesh/cmd-nse-simple-vl3-docker/blob/main/vppinit/vppinit.go#L51-L53
=> Remove TunnelIp env from the k8s_docker configuration

apps/nse-simple-vl3-docker/docker-compose.yaml, examples/k8s_monolith/dns/README.md, examples/k8s_monolith/spire/README.md, examples/k8s_monolith/usecases/Kernel2Wireguard2Kernel/README.md
We need this because updating the image tag is incorrect.
Closes: https://github.com/networkservicemesh/deployments-k8s/pull/6102
=> [qfix] Rename cmd-nse-simple-vl3-docker to nse-simple-vl3-docker

examples/use-cases/Kernel2RVlanMultiNS/README.md
Related issue: [cmd-nse-remote-vlan/18](https://github.com/networkservicemesh/cmd-nse-remote-vlan/issues/18)
Related PRs: [sdk-vpp/546](https://github.com/networkservicemesh/sdk-vpp/pull/546)
[cmd-forwarder-vpp/568](https://github.com/networkservicemesh/cmd-forwarder-vpp/pull/568)
Connect external interface directly (using vlan=0) and ping from outside the cluster
=> Connecting a remote interface without creating a VLAN on top

examples/features/scale-from-zero/pod-template.yaml
Sometimes `nodeName` is too long to be processed by spire
=> scale_form_zero: limit the length of the name

.github/workflows/ci.yaml
Delete `refcheck` job because updating references happens after push to the main branch
=> Delete refcheck job

examples/floating_interdomain/README.md, examples/floating_interdomain/usecases/FloatingVl3/README.md, examples/floating_interdomain/usecases/FloatingVl3/cluster1/kustomization.yaml, examples/floating_interdomain/usecases/FloatingVl3/cluster1/nsc-patch.yaml, examples/floating_interdomain/usecases/FloatingVl3/cluster1/nse-vl3-vpp.yaml, examples/floating_interdomain/usecases/FloatingVl3/cluster2/kustomization.yaml, examples/floating_interdomain/usecases/FloatingVl3/cluster2/nse-vl3-vpp.yaml, examples/floating_interdomain/usecases/FloatingVl3/cluster3/kustomization.yaml, examples/floating_interdomain/usecases/FloatingVl3/cluster3/patch-vl3-ipam.yaml
Main changes:
1. Fix link for the `cmd-nse-vl3-vpp` image
2. Add missed `patch-vl3-ipam.yaml`
3. Dynamic `NSM_PREFIXSERVERURL`
4. Use refs
Issue: https://github.com/networkservicemesh/deployments-k8s/issues/6345
=> Floating vl3 fix

apps/nsc-kernel-ponger/ponger.yaml, apps/nsc-vfio/nsc.yaml, apps/nse-vfio/nse-configmap.yaml, apps/nse-vfio/nse.yaml, examples/use-cases/Kernel2Kernel&Vfio2Noop/README.md, examples/use-cases/Kernel2Vxlan2Kernel&Vfio2Noop/README.md, examples/use-cases/Vfio2Noop/README.md
Issue: https://github.com/networkservicemesh/integration-k8s-packet/issues/295
Main changes:
1. `n3-xlarge` has other interface names (eno4 -> ens6f3)
2. Packet cluster API uses `containerd` instead of `docker` as a container runtime. `containerd` hasn't default limits. We need to set it manually using `ulimit`(required for SRIOV tests)
=> Fix vfio examples due to packet cluster api port

examples/spire/agent-daemonset.yaml
Signed-off-by: Szilard Vincze <szilard.vincze@est.tech>
- Mount bundle configmap volume in init-bundle container.
- Maximum retries increased to 60.
=> Complete workaround for spiffe/spire#3032 

examples/floating_interdomain/loadbalancer/README.md, examples/k8s_monolith/configuration/loadbalancer/README.md
Since metallb v0.12.1 we don't need to generate certs.
=> qfix: dont use openssl cert gen in interdomain examples

examples/features/dns/README.md
`nslookup` and `dig` use A question type by default.
Added A and AAAA requests.
https://github.com/networkservicemesh/integration-k8s-kind/issues/738
https://github.com/networkservicemesh/integration-k8s-aws/issues/324
=> dns test: send A and AAAA DNS requests

apps/nsmgr/nsmgr.yaml
`tcp://:5001` is used to automatically resolve public IP address.
But Pod may have predefined interfaces with any address. For example, there are 2 interfaces with IPv4 (predefined) and IPv6 (Pod interface). We are interested in IPv6, but IPv4 was automatically selected, and this is not correct.
We need to explicitly specify the Pod IP address
**_Note_**: brackets `[...]` work correctly for both IPv6 and IPv4
https://github.com/networkservicemesh/integration-k8s-kind/issues/738
https://github.com/networkservicemesh/integration-k8s-aws/issues/324
=> nsmgr: use specific IP for public address

examples/heal/local-nse-death/README.md
After deleting an endpoint, we can also get "Network unreachable" error.  We can get this when we don't have any IPv4 routes.
For example, this is possible if we have an ipv6 cluster and the pod doesn't have ipv4 addresses (and routes)
https://github.com/networkservicemesh/integration-k8s-kind/issues/738
https://github.com/networkservicemesh/integration-k8s-aws/issues/324
=> heal: handle "Network unreachable" error

examples/heal/dataplane-interrupt/README.md, examples/heal/local-nse-death/README.md
This PR adds ping source address to some heal tests. This is necessary to be sure that the ping comes from the nsm interface.
https://github.com/networkservicemesh/integration-k8s-packet/issues/306
=> Add ping source address to heal tests

.github/workflows/release.yaml, .github/workflows/update-dependent-repositories.yaml
Since go 1.17 `go get` is deprecated - https://go.dev/doc/go-get-install-deprecation
https://github.com/networkservicemesh/deployments-k8s/actions/runs/3527766888/jobs/5917182809
=> Replace "go get" with "go install"

examples/remotevlan/README.md, examples/use-cases/Kernel2RVlanMultiNS/README.md
The MTU value of the interface in NSC can not be bigger than the MTU value set on base interface
#7738
=> Add MTU adjustment checks in remote VLAN examples

apps/registry-k8s/registry-k8s.yaml
Related to 
https://github.com/networkservicemesh/deployments-k8s/issues/8187
https://github.com/networkservicemesh/cmd-registry-k8s/pull/360
=> qfix: Replace 'REGISTRY_K8S' to 'NSM' since registry-k8s env prefix updated

.github/workflows/pr-for-release.yaml
Replace deprecated Github Action
https://github.com/networkservicemesh/integration-k8s-packet/issues/312
=> Fix deprecated Github Action set-output

apps/nse-vl3-vpp/nse.yaml, examples/features/vl3-dns/README.md, examples/features/vl3-scale-from-zero/pod-template.yaml, examples/interdomain/nsm_consul_vl3/cluster1/nse-vl3-vpp/nse.yaml, examples/multicluster/usecases/floating_vl3-basic/cluster1/nse-vl3-vpp.yaml, examples/multicluster/usecases/floating_vl3-basic/cluster2/nse-vl3-vpp.yaml, examples/multicluster/usecases/floating_vl3-scale-from-zero/cluster1/pod-template.yaml, examples/multicluster/usecases/floating_vl3-scale-from-zero/cluster2/pod-template.yaml
If we add `POD_NAME` env to vl3-NSE we will be able to resolve endpoint DNS name
https://github.com/networkservicemesh/sdk/issues/1414
=> Add POD_NAME env to vl3-nse to be able to resolve the NSE name by DNS

examples/use-cases/SriovKernel2Noop/patch-nsc.yaml
For some reason, datapath connection between servers is not established for a long time. Because of this, the checker makes Closes/Requests endlessly.
Temporarily disable to look at the stability.
https://github.com/networkservicemesh/integration-k8s-packet/pull/318
=> Temporarily disable livenesscheck for SriovKernel2Noop

examples/multicluster/usecases/floating_nse_composition/cluster1/kustomization.yaml, examples/multicluster/usecases/floating_nse_composition/cluster1/nse-firewall/kustomization.yaml, examples/multicluster/usecases/floating_nse_composition/cluster2/kustomization.yaml
`bases` section in kustomization.yaml files is deprecated now.
=> Remove `bases` from kustomization files

apps/forwarder-vpp/forwarder.yaml, apps/nse-firewall-vpp/nse.yaml
Current `nse-firewall-vpp` and `forwarder-vpp` yaml files doesn't have memory requests, only memory limits. This PR adds memory requests for them based on these measurements:
```
NAME                                     CPU(cores)   MEMORY(bytes)
admission-webhook-k8s-84df466557-h6mw2   1m           20Mi
forwarder-vpp-477zp                      55m          324Mi
forwarder-vpp-s2fgm                      93m          336Mi
nsmgr-26w6p                              41m          67Mi
nsmgr-cqj8g                              16m          41Mi
registry-k8s-896d4b5c5-944dw             14m          33Mi
```
```
NAME                                 CPU(cores)   MEMORY(bytes)
alpine                               17m          17Mi
nse-firewall-vpp-6c5c6d4bd9-45q9z    383m         315Mi …
```
=> Add request memory values for `nse-firewall-vpp` and `forwarder-vpp`

apps/nse-kernel-ponger/ponger-configmap.yaml, apps/nse-kernel-ponger/ponger.yaml, apps/nse-noop/kustomization.yaml, apps/nse-noop/nse.yaml, apps/nse-vfio/nse-configmap.yaml, examples/use-cases/Kernel2Ethernet2Kernel_Vfio2Noop/README.md, examples/use-cases/Kernel2Ethernet2Kernel_Vfio2Noop/patch-nse-vfio.yaml, examples/use-cases/Kernel2Kernel_Vfio2Noop/README.md, examples/use-cases/Kernel2Kernel_Vfio2Noop/patch-nse-vfio.yaml, examples/use-cases/SriovKernel2Noop/README.md, examples/use-cases/SriovKernel2Noop/kustomization.yaml, examples/use-cases/SriovKernel2Noop/patch-nse.yaml, examples/use-cases/Vfio2Noop/README.md, examples/use-cases/Vfio2Noop/patch-nse-vfio.yaml
To work with VLAN tags, we need slightly change the configuration of the examples.
https://github.com/networkservicemesh/sdk-sriov/issues/489
=> Fix SRIOV examples to work with VLAN tags

examples/afxdp/README.md
So many tests don't make sense, it just wastes time. AF_XDP only affects remote cases.
This PR will allow us to run tests on public clusters without increasing the time too much.
I left here only remote cases, as well as a few examples from features.
https://github.com/networkservicemesh/cmd-forwarder-vpp/issues/859
https://github.com/networkservicemesh/integration-k8s-gke/issues/383
=> Reduce the number of af_xdp tests

apps/admission-webhook-k8s/service.yaml, apps/registry-k8s/registry-service.yaml, apps/registry-memory/registry-service.yaml, apps/registry-proxy-dns/registry-proxy-service.yaml, apps/vl3-ipam/vl3-ipam-service.yaml, examples/multicluster/clusters-configuration/cluster1/kustomization.yaml, examples/multicluster/clusters-configuration/cluster1/patch-registry-service.yaml, examples/multicluster/clusters-configuration/cluster2/kustomization.yaml, examples/multicluster/clusters-configuration/cluster2/patch-registry-service.yaml, examples/multicluster/clusters-configuration/cluster3/kustomization.yaml, examples/multicluster/clusters-configuration/cluster3/patch-registry-service.yaml, examples/spire/base/server-service.yaml, examples/spire/cluster1/kustomization.yaml, examples/spire/cluster1/service-patch.yaml, examples/spire/cluster2/kustomization.yaml, examples/spire/cluster2/service-patch.yaml, examples/spire/cluster3/kustomization.yaml, examples/spire/cluster3/service-patch.yaml
Currently, testing with single cluster public clusters could affect interdomain testing because we're using loadbalancer services (cluster provider will allocate load banacer server for singlecluster and for interdomain when we don't need loadbalancers for single cluster testing).
=> Optimize the loadbalacer usage for examples

apps/admission-webhook-k8s/admission-webhook.yaml
Allow configuration of initContainer resource requests and limits
Prerequisite PR in `cmd-admission-webhook-k8s`: https://github.com/networkservicemesh/cmd-admission-webhook-k8s/pull/321
As I can see image `admission-webhook-k8s` is updated after merge prerequisite PR https://github.com/networkservicemesh/deployments-k8s/pull/9728/files, so we can merge this changes
https://github.com/networkservicemesh/cmd-admission-webhook-k8s/issues/292
=> Task 292 Feature Request: Allow configuration of initContainer resource requests and limits

examples/features/vl3-lb/README.md
The "finance" name has conflicts on public clusters
https://github.com/networkservicemesh/deployments-k8s/issues/9210
=> [qfix] vl3-lb: add service name to dns request

apps/nsmgr-proxy/nsmgr-proxy.yaml, apps/nsmgr/nsmgr.yaml, apps/registry-k8s/registry-k8s.yaml, apps/registry-memory/registry-memory.yaml, apps/registry-proxy-dns/registry-proxy-dns.yaml, apps/vl3-ipam/vl3-ipam.yaml, examples/interdomain/nsm_consul_vl3/cluster1/vl3-ipam/vl3-ipam.yaml
Currently many of our core apps declare host ports. However, we don't need host ports, we use LoadBalancer type services when we need external connectivity.
=> [quick fix] Remove hostport from apps

apps/forwarder-vpp/forwarder.yaml, examples/basic/forwarder-patch.yaml, examples/basic/kustomization.yaml, examples/features/select-forwarder/forwarder.yaml
`forwarder-vpp` has config variable `NSM_TUNNEL_IP` which is currently used to determine the interface the forwarder will use for data plane connection.
When `NSM_TUNNEL_IP` is not set, `forwarder-vpp` automatically selects default interface instead (interface with default route). `NSM_TUNNEL_IP` was intended to be used to override this behavior in case you want to use a different interface.
We actually want to use the default interface instead of setting `NSM_TUNNEL_IP` manually.
https://github.com/networkservicemesh/deployments-k8s/issues/10021
=> Disable tunnel IP override in forwarder-vpp

apps/nsmgr-proxy/nsmgr-proxy.yaml, apps/nsmgr/nsmgr.yaml, apps/registry-k8s/registry-k8s.yaml, apps/registry-memory/registry-memory.yaml, apps/registry-proxy-dns/registry-proxy-dns.yaml, apps/vl3-ipam/vl3-ipam.yaml, examples/interdomain/nsm_consul_vl3/cluster1/vl3-ipam/vl3-ipam.yaml
This reverts commit 3ebf1bf0881f6851d205b863d97bd3ff32bce9f7.
Issue: https://github.com/networkservicemesh/deployments-k8s/issues/10021
This PR should theoretically fix interdomain tests here: https://github.com/networkservicemesh/integration-k8s-kind/pull/903
=> Revert host port changes

.github/workflows/check-cves.yaml
Improve CVEs scanning workflow:
1. Run only once a week
2. Added image names for each CVE
3. Removing all old CVEs before new scanning
https://github.com/networkservicemesh/deployments-k8s/issues/10726
=> Improve check CVEs cronjob

examples/heal/spire-server-restart/README.md, examples/spire/base/server-statefulset.yaml
Spire-server requires `PersistentVolume` for `/run/spire/data`.
Apparently, if the server is restarted, this data is used to issue the correct certificates.
If we don't use the PersistentVolume, then _new_ and _old_ certificates are not compatible with each other.
See manuals:
> If you are using Kubeadm to run this tutorial, a default storage class and an associated provisioner must be manually created, otherwise the spire-server pod will stay in Pending status, showing the 1 pod has unbound immediate PersistentVolumeClaims error. 
https://spiffe.io/docs/latest/try/getting-started-k8s/#overview
Example:
https://github.com/spiffe/spire-tutorials/blob/main/k8s/quickstart/server-statefulset.yaml#L54-L63
https://github.com/networkservicemesh/deployments-k8s/issues/10286
=> Add volumeClaimTemplates to the spire-server statefulset

examples/features/jaeger/README.md, examples/heal/spire-server-agent-restart/README.md, examples/heal/spire-server-restart/README.md, examples/heal/spire-upgrade/README.md, examples/spire/cluster1/README.md, examples/spire/cluster2/README.md, examples/spire/cluster3/README.md, examples/spire/single_cluster/README.md, examples/spire/single_cluster_csi/README.md
Attaching a volume sometimes takes time:
```
Normal  Scheduled               57s   default-scheduler        Successfully assigned spire/spire-server-0 to aks-nodepool1-24896710-vmss000001
Normal  SuccessfulAttachVolume  0s    attachdetach-controller  AttachVolume.Attach succeeded for volume "pvc-3c0c4cc6-87fb-46fd-a7cc-1c2085bb56f2" TestRunBasicSuite=stdout
```
https://github.com/networkservicemesh/deployments-k8s/issues/10286
=> Increase spire-server wait

examples/heal_extended/README.md, examples/heal_extended/component-restart/README.md, examples/heal_extended/component-restart/client-cp.yaml, examples/heal_extended/component-restart/client.yaml, examples/heal_extended/component-restart/kustomization.yaml, examples/heal_extended/component-restart/netsvc.yaml, examples/heal_extended/component-restart/ns-component-restart.yaml, examples/heal_extended/component-restart/patch-nse.yaml
Unlike standard heal tests, these tests are more aggressive and require more execution time
**Test Component Restart**
(takes about 45 min on kind cluster)
Restarts the NSM component several times in different modes - all instances or one by one. The current PR contains only the Forwarder check, but can be extended to NSMgr.
https://github.com/networkservicemesh/deployments-k8s/issues/10918
=> Heal extended test: component restarts

examples/features_ovs/README.md, examples/heal/local-forwarder-death/README.md, examples/heal/local-forwarder-remote-forwarder/README.md, examples/heal/registry-remote-forwarder/README.md, examples/heal/remote-forwarder-death-ip/README.md, examples/heal/remote-forwarder-death/README.md, examples/heal_ovs/README.md, examples/ovs/README.md
New tests added to ovs suite.
Related issue: networkservicemesh/deployments-k8s#9778
=> Add feature test cases to ovs suite

.github/workflows/release.yaml
https://github.com/networkservicemesh/.github/issues/58
=> Create releases with Github CLI

examples/k8s_monolith/external_nsc/dns/README.md, examples/k8s_monolith/external_nse/dns/README.md
We shouldn't run `docker exec` command in the background for these cases
The dns configuration has also been fixed, since `file` and `forward` plugins cannot be located on the same server.
Closes: https://github.com/networkservicemesh/deployments-k8s/issues/11229
=> Fix monolith docker dns

apps/registry-memory/registry-memory.yaml
The prefix used in `cmd-registry-memory` for `envconfig.Usage` got changed to 'nsm', so I'm updating this too.
[ Keep env var descriptions in sync in cmd and README.md #65 ](https://github.com/networkservicemesh/.github/issues/65)
- [ x ] Have not tested
- [ x ] Refactoring
- [ x ] CI
=> Update env vars of registry-memory

apps/nsc-vfio/nsc.yaml, apps/nsmgr-proxy/nsmgr-proxy.yaml, examples/heal_extended/component-restart/client-cp.yaml, examples/pss/nsm-system/patch-admission-webhook-k8s.yaml
I've put the split_words:"true" to some env vars, as discussed, so there was a need to change 
the envs here too. Now when doing the pull request I've discovered that I've updated some of the deprecated repos too, so some of the envs below might not be relevant, haven't double checked it yet.
NSM_ACL_CONFIG
NSM_BRIDGE_NAME
NSM_FEDERATES_WITH
NSM_INTERFACE_NAME
NSM_LIVENESS_CHECK_ENABLED
NSM_LIVENESS_CHECK_INTERVAL
NSM_LIVENESS_CHECK_TIMEOUT
NSM_LOCAL_DNS_SERVER_ADDRESS
NSM_LOCAL_DNS_SERVER_ENABLED
NSM_METRICS_EXPORT_INTERVAL
NSM_NODE_NAME
NSM_OPEN_TELEMETRY_ENDPOINT
NSM_OUTPUT_PATH
NSM_TRUST_DOMAIN
NSM_VL3_PREFIX
- [ x ] Have not tested
- [ x ] CI
=> Align env vars

apps/forwarder-vpp/forwarder.yaml, apps/nsmgr/nsmgr.yaml, apps/registry-k8s/registry-k8s.yaml
Envs should all be strings only. 
https://github.com/networkservicemesh/integration-k8s-kind/pull/1026
=> Fix envs in cmd-nsmgr, cmd-forwarder-vpp and cmd-registry

.github/workflows/check-tag.yaml, apps/forwarder-vpp/forwarder.yaml, apps/nsmgr/nsmgr.yaml, apps/registry-k8s/registry-k8s.yaml
Added configuration for turning profiling on/off.
https://github.com/networkservicemesh/deployments-k8s/issues/12045
=> Rename NSM_PPROF_PORT env to NSM_PPROF_LISTEN_ON and update value

examples/spire/cluster1/kustomization.yaml, examples/spire/cluster1/server.conf, examples/spire/cluster2/kustomization.yaml, examples/spire/cluster2/server.conf, examples/spire/cluster3/kustomization.yaml, examples/spire/cluster3/server.conf
Extended config for interdomain tests. Main PR - https://github.com/networkservicemesh/deployments-k8s/pull/12120
https://github.com/networkservicemesh/deployments-k8s/issues/12072
=> Add PostgreSQL server to the spire server config and get rid of using persistent volume - interdomain tests

apps/admission-webhook-k8s/kustomization.yaml
=> [qfix] remove unnecessary `namespace` field in admission-webhook's `kustomization.yaml`

examples/interdomain/three_cluster_configuration/spiffe_federation/README.md
The -c flag in the kubectl exec command specifies which container in a pod you want to execute the command against. This is necessary when a pod has multiple containers, and you need to indicate which container should run the command.
If the -c flag is not passed, the command is executed, however a messagem is popupd, and in automated scripts it invalidade the processo.
The adition of -c will not affect the manual usage and will prevent erros in some automation process.
Summary
Use -c when the pod has multiple containers.
It ensures you are executing the command in the correct container. Helps avoid unexpected behavior or errors when Kubernetes defaults to the wrong container.
=> Update README.md to included -c flag

examples/features/ipam-policies/README.md
Test have been failing in case first client had 172.16.1.2 as dst. It is expected to ping here from alpine-1 pod to check both addresses - one is acceptable for the first client, the other for second. 
https://github.com/networkservicemesh/integration-k8s-kind/issues/1042
=> Fix ipam policies ping command

external-images.yaml
Adds the Kuma image to `external-images.yaml` to prevent test timeouts from image pulling.
=> Add Kuma image to the external images
