- .github/workflows/pr-for-updates.yaml
Example: https://github.com/networkservicemesh/deployments-k8s/runs/1621346234
> fix:  PRs from cmd-* repos can not be opened

- examples/memory/kustomization.yaml
> fix typo for memory registry tests

- .github/workflows/update-dependent-repositories.yaml
This PR allows to repository deployments-k8s do updates to integration-tests.
> feat: add update deps job for deployments-k8s

- .github/workflows/ci.yaml
- .github/workflows/update-dependent-repositories.yaml
> Fix: Update deps job is not working

- examples/use-cases/RemoteConnection/README.md
> Do not wait logs in tests

- .github/workflows/ci.yaml
> Fix: update deps job is not start by NSMBot

- examples/sriov/README.md
Signed-off-by: Vladimir Popov <vladimir.popov@xored.com>
> Fix sriov dependencies

- .github/workflows/ci.yaml
Closes https://github.com/networkservicemesh/deployments-k8s/issues/475
> fix: 'Automerge job can stuck and do not merge green PRs from NSMBot'

- apps/nse-vfio/nse-configmap.yaml
- apps/nse-vfio/nse.yaml
- examples/use-cases/Memif2Kernel/README.md
Fix for https://github.com/networkservicemesh/integration-k8s-kind/pull/145.
> Add missed suffixes

- .github/workflows/update-dependent-repositories.yaml
Related to https://github.com/networkservicemesh/deployments-k8s/pull/726
> fix: deployments-k8s cannot update integration-tests 

- apps/forwarder-vpp/forwarder.yaml
- apps/nsc-memif/nsc.yaml
- apps/nse-memif/nse.yaml
> Add requests resourses for vpp apps

- README.md
- examples/features/README.md
- examples/features/dns/README.md
- examples/features/dns/coredns-config-map.yaml
Closes https://github.com/networkservicemesh/deployments-k8s/issues/741
> End to end DNS integration: add DNS examples

- examples/features/dns/README.md
Fixes https://github.com/networkservicemesh/integration-k8s-kind/pull/192
> qfix: Make sure that wh has started

- apps/nsmgr/nsmgr.yaml
Signed-off-by: Ed Warnicke <hagbard@gmail.com>
> Add readiness and liveliness probe to nsmgr

- apps/forwarder-vpp/forwarder.yaml
This will be needed for interdomain.
Signed-off-by: Ed Warnicke <hagbard@gmail.com>
> Add hostNetwork:true to apps/forwarder.yaml

- apps/admission-webhook-k8s/admission-webhook.yaml
- apps/forwarder-sriov/forwarder.yaml
- apps/forwarder-vpp/forwarder.yaml
- apps/nsc-kernel/nsc.yaml
- apps/nsc-memif/nsc.yaml
- apps/nsc-vfio/nsc.yaml
- apps/nse-kernel/nse.yaml
- apps/nse-memif/nse.yaml
- apps/nse-supplier-k8s/supplier.yaml
- apps/nse-vfio/nse.yaml
- apps/nsmgr/nsmgr.yaml
- apps/registry-k8s/registry-k8s.yaml
- apps/registry-memory/registry-memory.yaml
- examples/features/scale-from-zero/pod-template.yaml
> Adapt apps to use "ghcr.io/${{ github.repository_owner }}/ci/${{ github.event.repository.name }}" pattern

- .github/workflows/update-dependent-repositories.yaml
FIxes: https://github.com/networkservicemesh/deployments-k8s/runs/2749397599?check_suite_focus=true
The problem started reproducing two days ago: https://github.com/networkservicemesh/integration-tests/commit/a09f0b1d70945e7dccfc5dd72f7020055f9971d1
> Update go version to 1.16

- README.md
- examples/features/README.md
- examples/features/scale-from-zero/autoscale-netsvc.yaml
https://github.com/networkservicemesh/sdk/issues/892
> [qfix] Add link to scale from zero to main readme

- README.md
- examples/heal/local-forwarder-healing/README.md
fixes https://github.com/networkservicemesh/deployments-k8s/issues/1693
> Fixed local forwarder test

- README.md
- apps/nsmgr-proxy/nsmgr-proxy.yaml
- examples/floating/README.md
- examples/floating/kustomization.yaml
- examples/floating/usecases/Kernel2Vxlan2Kernel/README.md
> fix: Add interdomain examples into README.md

- .github/workflows/ci.yaml
- .github/workflows/release.yaml
- .github/workflows/update-dependent-repositories.yaml
> feat: Add release actions

- .github/workflows/release.yaml
> fix: Add missed GitHub expression for release action

- .github/workflows/release.yaml
> fix: error "sed: -e expression #1, char 57: unknown option to `s'" on release

- examples/features/README.md
- examples/features/ipv6/Kernel2Wireguard2Kernel/README.md
- examples/features/ipv6/Kernel2Wireguard2Memif/README.md
- examples/features/ipv6/Memif2Wireguard2Kernel/README.md
- examples/features/ipv6/Memif2Wireguard2Memif/README.md
> Add wireguard example IPv6

- examples/heal/README.md
Issues where it will be solved:
https://github.com/networkservicemesh/deployments-k8s/issues/2065
https://github.com/networkservicemesh/deployments-k8s/issues/2066
> Disable unstable heal tests

- examples/features/scale-from-zero/autoscale-netsvc.yaml
fixes #2007
After changes in api and sdk for using multiple matches merged i've changed scale-from-zero example.
> Changed scale-from-zero for using multiple matches

- examples/heal/README.md
It will be solved here:
https://github.com/networkservicemesh/deployments-k8s/issues/2087
> Disable unstable heal Local-Forwarder-death test

- examples/features/nse-composition/README.md
Fix for preventing crashloopbackoff of nse pod
fixes https://github.com/networkservicemesh/integration-k8s-gke/issues/100
> Increased client request timeout

- examples/features/nse-composition/nse-composition-ns.yaml
fixes https://github.com/networkservicemesh/deployments-k8s/issues/2140
> Removed duplicate name

- apps/nse-kernel/nse.yaml
- examples/features/dns/README.md
- examples/features/ipv6/Kernel2Kernel/README.md
- examples/features/ipv6/Kernel2Wireguard2Kernel/README.md
- examples/features/ipv6/Memif2Wireguard2Kernel/README.md
- examples/features/nse-composition/README.md
- examples/features/opa/README.md
- examples/features/scale-from-zero/pod-template.yaml
- examples/features/webhook/README.md
- examples/floating/usecases/Kernel2Vxlan2Kernel/README.md
- examples/heal/local-forwarder-death/README.md
- examples/heal/local-nse-death/README.md
- examples/heal/local-nsmgr-restart/README.md
- examples/heal/registry-restart/README.md
- examples/heal/remote-forwarder-death/README.md
- examples/heal/remote-nse-death/README.md
- examples/heal/remote-nsmgr-death/README.md
- examples/heal/remote-nsmgr-restart/README.md
- examples/interdomain/usecases/Kernel2Vxlan2Kernel/README.md
- examples/use-cases/Kernel2Kernel&Vfio2Noop/README.md
- examples/use-cases/Kernel2Kernel/README.md
- examples/use-cases/Kernel2Vxlan2Kernel/README.md
- examples/use-cases/Kernel2Wireguard2Kernel/README.md
- examples/use-cases/Memif2Kernel/README.md
- examples/use-cases/Memif2Vxlan2Kernel/README.md
- examples/use-cases/Memif2Wireguard2Kernel/README.md
- examples/use-cases/SriovKernel2Noop/README.md
Issue: https://github.com/networkservicemesh/cmd-nse-icmp-responder/issues/246
Must be merged along with https://github.com/networkservicemesh/cmd-nse-icmp-responder/pull/249
> Update examples to support multi-ns icmp-responder

- apps/registry-k8s/registry-k8s.yaml
Closes https://github.com/networkservicemesh/deployments-k8s/pull/2298.
> Manually update registry-k8s version

- .github/workflows/automerge.yaml
- .github/workflows/pr-for-updates.yaml
- .github/workflows/update-dependent-repositories.yaml
part of https://github.com/networkservicemesh/cmd-template/issues/64
> Updated nsmbot message

- examples/features/ipv6/Kernel2Wireguard2Kernel/README.md
- examples/features/ipv6/Kernel2Wireguard2Memif/README.md
- examples/features/ipv6/Memif2Wireguard2Kernel/README.md
- examples/features/ipv6/Memif2Wireguard2Memif/README.md
- examples/use-cases/Kernel2Wireguard2Kernel/README.md
- examples/use-cases/Kernel2Wireguard2Memif/README.md
- examples/use-cases/Memif2Wireguard2Kernel/README.md
- examples/use-cases/Memif2Wireguard2Memif/README.md
fixes https://github.com/networkservicemesh/sdk/issues/1048
> Renamed ns in few tests

- .github/workflows/update-dependent-repositories.yaml
> Updated sha retrieving

- examples/features/ipv6/Kernel2Wireguard2Memif/README.md
- examples/features/ipv6/Memif2Memif/README.md
- examples/features/ipv6/Memif2Wireguard2Memif/README.md
- examples/use-cases/Kernel2Memif/README.md
- examples/use-cases/Kernel2Vxlan2Memif/README.md
- examples/use-cases/Kernel2Wireguard2Memif/README.md
- examples/use-cases/Memif2Memif/README.md
- examples/use-cases/Memif2Vxlan2Memif/README.md
- examples/use-cases/Memif2Wireguard2Memif/README.md
> qfix: change payload prefix to NSM for memif-nses

- examples/features/dns/README.md
Ping `google.com` in DNS test.
networkservicemesh/deployments-k8s#2689
> [deployments-k8s#2689] Ping google.com in DNS test

- apps/nse-vfio/nse.yaml
- examples/features/dns/README.md
- examples/features/webhook/README.md
- examples/spire/agent-daemonset.yaml
> Add IfNotPresent to the appropriate containers

- examples/spire/server-service.yaml
Fixes https://github.com/networkservicemesh/integration-k8s-kind/pull/371
> qfix: Remove typo with type of spire-service

- examples/spire/agent-daemonset.yaml
- examples/spire/server-statefulset.yaml
related to https://github.com/networkservicemesh/deployments-k8s/issues/2818
> Update spire agent and server images to 1.0.2

- examples/spire/server.conf
https://github.com/networkservicemesh/deployments-k8s/pull/2901
Closes https://github.com/networkservicemesh/integration-k8s-kind/pull/388
> qfix: spire server cannot start after update

- examples/interdomain/spire/cluster1/server.conf
- examples/interdomain/spire/cluster2/server.conf
- examples/interdomain/spire/cluster3/server.conf
https://github.com/networkservicemesh/deployments-k8s/pull/2901
Fixes failed interdomain tests
> Removed deprecated field in spire configs after update

- examples/multiforwarder/README.md
- examples/multiforwarder/kustomization.yaml
- examples/use-cases/Kernel2Kernel&Vfio2Noop/README.md
- examples/use-cases/Kernel2Vxlan2Kernel&Vfio2Noop/README.md
Restores back multiforwarder test cases with SR-IOV and VPP forwarders.
networkservicemesh/sdk-vpp#314
> [sdk-vpp#314] Restore multiforwarder test cases

- .github/workflows/update-dependent-repositories.yaml
> [qfix] Fix github action to get hash of PR

- .gitignore
Signed-off-by: Tim Swanson <tiswanso@cisco.com>
> gitignore: Add emacs and vscode tmp files

- apps/forwarder-sriov/forwarder.yaml
- apps/forwarder-vpp/forwarder.yaml
fixes #2929
Signed-off-by: Tim Swanson <tiswanso@cisco.com>
> Set dnsPolicy to ClusterFirstWithHostNet for forwarder daemonsets

- apps/nsc-kernel/nsc.yaml
- apps/nsc-vfio/nsc.yaml
- apps/nse-firewall-vpp/nse.yaml
- apps/nse-kernel/nse.yaml
- apps/nse-vfio/nse.yaml
- apps/nsmgr-proxy/nsmgr-proxy.yaml
- apps/nsmgr/nsmgr.yaml
- apps/registry-memory/registry-memory.yaml
- apps/registry-proxy-dns/registry-proxy-dns.yaml
- examples/features/nse-composition/passthrough-1.yaml
- examples/features/nse-composition/passthrough-2.yaml
- examples/features/nse-composition/passthrough-3.yaml
Increases memory limits for applications to make them work for a long time.
#2381
> [deployments-k8s#2381] Tune memory limits

- examples/sriov/README.md
- examples/sriov/forwarder-vpp.yaml
- examples/sriov/kustomization.yaml
For correct work of kustomization
https://github.com/networkservicemesh/integration-k8s-packet/pull/133
> Pull out forwarder-vpp patch

- .github/workflows/update-refs.yaml
> Fix "Update references" action

- examples/interdomain/README.md
- examples/interdomain/loadbalancer/README.md
- examples/interdomain/usecases/FloatingKernel2Vxlan2Kernel/README.md
- examples/interdomain/usecases/Kernel2Vxlan2Kernel/README.md
Fixes for some unstable points which made interdomain tests fail because of setup issues and not because of tests themselves.
> Quickfix for stability improvements of interdomain tests

- .github/workflows/update-refs.yaml
> Fix "Update references"

- apps/registry-k8s/crd-ns.yaml
- apps/registry-k8s/crd-nse.yaml
Fixes https://github.com/networkservicemesh/integration-k8s-kind/pull/411
> fix: Add schema for NSM CRDs

- examples/ovs/README.md
Signed-off-by: Periyasamy Palanisamy <periyasamy.palanisamy@est.tech>
> remove spire registration for nsm-system namespace

- apps/admission-webhook-k8s/admission-webhook.yaml
- apps/forwarder-host-ovs/forwarder.yaml
- apps/forwarder-ovs/forwarder.yaml
- apps/forwarder-sriov/forwarder.yaml
- apps/forwarder-vpp/forwarder.yaml
- apps/nsc-kernel/nsc.yaml
- apps/nsc-memif/nsc.yaml
- apps/nsc-vfio/nsc.yaml
- apps/nse-firewall-vpp/nse.yaml
- apps/nse-kernel/nse.yaml
- apps/nse-memif/nse.yaml
- apps/nse-supplier-k8s/supplier.yaml
- apps/nse-vfio/nse.yaml
- apps/nsmgr-proxy/nsmgr-proxy.yaml
- apps/nsmgr/nsmgr.yaml
- apps/registry-k8s/registry-k8s.yaml
- apps/registry-memory/registry-memory.yaml
- apps/registry-proxy-dns/registry-proxy-dns.yaml
https://github.com/networkservicemesh/sdk/issues/1008
Added to all deployments env variable `log level` with default value `trace`
> Default log level

- .github/workflows/update-dependent-repositories.yaml
Fixes sha update script.
https://github.com/networkservicemesh/integration-tests/pull/912
https://github.com/networkservicemesh/integration-tests/blob/8982bfaed7c46ecf05c1c2e035790cc599bc3e8d/extensions/base/suite.go#L54
> [qfix] Fix invalid sha update

- examples/features/nse-composition/README.md
- examples/features/nse-composition/nse-composition-ns.yaml
https://github.com/networkservicemesh/sdk-k8s/issues/252
> changed namespace for ns

- examples/heal/README.md
- examples/heal/local-forwarder-death/README.md
- examples/heal/remote-forwarder-death-ip/README.md
- examples/heal/remote-nse-death-ip/README.md
- examples/heal/remote-nsmgr-restart-ip/README.md
- examples/heal/remote-nsmgr-restart/README.md
> Enable heal tests

- apps/nsc-memif/nsc.yaml
- examples/heal/local-forwarder-death/README.md
- examples/heal/local-nse-death/README.md
- examples/heal/local-nsmgr-restart/README.md
- examples/heal/registry-restart/README.md
- examples/heal/remote-forwarder-death-ip/README.md
- examples/heal/remote-forwarder-death/README.md
- examples/heal/remote-nse-death-ip/README.md
- examples/heal/remote-nse-death/README.md
- examples/heal/remote-nsmgr-death/README.md
- examples/heal/remote-nsmgr-restart-ip/README.md
- examples/heal/remote-nsmgr-restart/README.md
Closes: https://github.com/networkservicemesh/deployments-k8s/issues/3677
> Remove extra NSM_REQUEST_TIMEOUT envs

- apps/nse-memif/nse.yaml
- apps/nse-supplier-k8s/supplier.yaml
- apps/nse-vfio/nse.yaml
- examples/features/scale-from-zero/README.md
> [qfix] Replace NSM_* to NSE_* env prefix

- examples/features/nse-composition/README.md
- examples/features/nse-composition/nse-firewall/patch-nse-firewall-vpp.yaml
- examples/features/nse-composition/passthrough-1.yaml
- examples/features/nse-composition/passthrough-2.yaml
- examples/features/nse-composition/passthrough-3.yaml
- examples/features/scale-from-zero/pod-template.yaml
- examples/use-cases/SmartVF2SmartVF/README.md
- examples/use-cases/SriovKernel2Noop/README.md
Changed value for `NSM_LABELS` env variable to be reference to `metadata.labels` for each place this variable used.
closes https://github.com/networkservicemesh/deployments-k8s/issues/3437
> Switched to metadata.labels

- README.md
- examples/features/webhook-smartvf/.gitignore
- examples/features/webhook-smartvf/README.md
Signed-off-by: Dimitrios Markou <dimitrios.markou@est.tech>
> Add Webhook SmartVF example

- apps/nsmgr/role.yaml
> fix/added missed rules for correct work of exclude-prefixes

- README.md
- examples/ovs/README.md
Signed-off-by: Dimitrios Markou <dimitrios.markou@est.tech>
> Add webhook smartvf example under ovs Readme

- .github/workflows/update-dependent-repositories.yaml
> fix for correct generation in integration-tests

- examples/heal/local-forwarder-death/README.md
- examples/heal/remote-forwarder-death-ip/README.md
- examples/heal/remote-forwarder-death/README.md
- examples/heal/remote-nsmgr-restart-ip/README.md
- examples/heal/remote-nsmgr-restart/README.md
> Replace `/30` mask with `/31` for heal tests

- apps/nse-vlan-vpp/kustomization.yaml
- apps/nse-vlan-vpp/nse.yaml
- examples/ovs/README.md
- examples/use-cases/Kernel2KernelVLAN/README.md
Signed-off-by: Periyasamy Palanisamy <periyasamy.palanisamy@est.tech>
> add vlan trunking markdown examples

- examples/features/scale-from-zero/pod-template.yaml
> fixed log level for pod template

- apps/registry-k8s/registry-k8s.yaml
- apps/registry-memory/registry-memory.yaml
> [qfix] Fix registry loglevel env name

- doc/SRIOV_config.md
- examples/multiforwarder/README.md
- examples/ovs/README.md
- examples/sriov/README.md
Adds documentation about SR-IOV configuration.
Closes networkservicemesh/integration-k8s-packet#105.
> [integration-k8s-packet#105] SR-IOV config

- apps/nsmgr/nsmgr.yaml
Potentially closes https://github.com/networkservicemesh/deployments-k8s/issues/2766
> qfix: Increase memory limits for nsmgr

- apps/nsc-kernel/nsc.yaml
- apps/nse-kernel/nse.yaml
Potentially fixes OOM from https://github.com/networkservicemesh/deployments-k8s/issues/3771
> qfix: Increase memory limits for nsc-kernel and nse-kernel

- .github/workflows/release.yaml
> qfix: Update release.yaml to latest changes

- apps/admission-webhook-k8s/admission-webhook.yaml
closes https://github.com/networkservicemesh/deployments-k8s/issues/3986
> Added correct log level to webhook envs

- examples/features/select-forwarder/service.yaml
Closes https://github.com/networkservicemesh/integration-k8s-kind/pull/505
> qfix: networkservice is incorrect for example 'select forwarder'

- examples/features/select-forwarder/service.yaml
> [qfix] Add missed quotes

- examples/interdomain/README.md
- examples/interdomain/usecases/FloatingKernel2Wireguard2Kernel/README.md
- examples/interdomain/usecases/Kernel2Wireguard2Kernel/README.md
Closes https://github.com/networkservicemesh/deployments-k8s/issues/3954
> feat: Add more floating interdomain/interdomain examples(IP payload)

- .github/workflows/ci.yaml
Closes https://github.com/networkservicemesh/integration-tests/pull/1203
Closes https://github.com/networkservicemesh/integration-tests/issues/1197
Closes https://github.com/networkservicemesh/integration-tests/issues/1192
> feat: Add images check action

- .github/workflows/ci.yaml
> fix: image-check job skips NSMBot updates

- examples/heal/README.md
- examples/heal/local-forwarder-remote-forwarder/README.md
- examples/heal/local-nsm-system-restart/README.md
- examples/heal/local-nsmgr-local-forwarder-memif/README.md
- examples/heal/local-nsmgr-local-nse-memif/README.md
- examples/heal/local-nsmgr-remote-nsmgr/README.md
- examples/heal/registry-local-endpoint/README.md
- examples/heal/registry-remote-forwarder/README.md
- examples/heal/registry-remote-nsmgr/README.md
- examples/heal/remote-nsm-system-restart-memif-ip/README.md
- examples/heal/remote-nsmgr-remote-endpoint/README.md
Issue: https://github.com/networkservicemesh/sdk/issues/1196
> Add advanced healing tests

- examples/heal/README.md
https://github.com/networkservicemesh/integration-k8s-kind/pull/539
Will be solved here: https://github.com/networkservicemesh/deployments-k8s/issues/4219
> Temporarily disable TestRemote_nsm_system_restart_memif_ip

- examples/heal/README.md
This reverts commit 67a064b83fbb2aad5f25f37198e61d44bd946541.
Issue: https://github.com/networkservicemesh/deployments-k8s/issues/4219
> Revert "Temporarily disable TestRemote_nsm_system_restart_memif_ip"

- examples/heal/README.md
Issue: https://github.com/networkservicemesh/deployments-k8s/issues/4247
Issue: https://github.com/networkservicemesh/deployments-k8s/issues/4248
> Temporarily disable unstable tests

- examples/calico/README.md
part of https://github.com/networkservicemesh/integration-k8s-kind/issues/325
> Changed calico suite

- .github/workflows/automerge.yaml
- .github/workflows/ci.yaml
- .github/workflows/pr-for-release.yaml
- .github/workflows/release.yaml
https://github.com/networkservicemesh/deployments-k8s/issues/4271
> Fan-in NSM Releasing

- examples/observability/jaeger-and-prometheus/README.md
> Add links to observability example

- examples/observability/jaeger-and-prometheus/README.md
> add forwarder metrics retrieval

- examples/heal/README.md
I run these tests on my local cluster a few times and it seems to me they're fine for now. Let's check them on other k8s versions and public clusters.
> feat: Enable registry adv heal tests

- examples/basic/README.md
- examples/calico/README.md
- examples/heal/local-nsm-system-restart/README.md
- examples/heal/remote-nsm-system-restart-memif-ip/README.md
- examples/memory/README.md
- examples/multiforwarder/README.md
- examples/observability/jaeger-and-prometheus/README.md
- examples/ovs/README.md
- examples/remotevlan/README.md
- examples/sriov/README.md
Closes: https://github.com/networkservicemesh/deployments-k8s/issues/4468
> Delete only NSM admission-webhook

- examples/observability/jaeger-and-prometheus/README.md
- external-images.yaml
> Add external images

- examples/heal/local-nsmgr-local-nse-memif/README.md
Issue: https://github.com/networkservicemesh/integration-k8s-aks/issues/185
Delete the previous NSE before the new one
> TestLocal_nsmgr_local_nse_memif fix

- examples/heal/README.md
Issue: https://github.com/networkservicemesh/deployments-k8s/issues/4248
> Enable heal test: NSM system restart - remote memif ip-payload

- examples/features/select-forwarder/service.yaml
Closes https://github.com/networkservicemesh/deployments-k8s/issues/4008
> refactor: Remove empty destination_selector

- examples/features/select-forwarder/service.yaml
Contunues https://github.com/networkservicemesh/deployments-k8s/pull/4548
> qfix: Add missed routes for select forwarder example

- examples/features/select-forwarder/service.yaml
Simplifies https://github.com/networkservicemesh/deployments-k8s/pull/4551
> refactor: simplify select-forwarder example

- .github/workflows/automerge.yaml
https://github.com/networkservicemesh/deployments-k8s/issues/4271
> Add auto-delete job for release branch

- .github/workflows/automerge.yaml
- .github/workflows/ci.yaml
https://github.com/networkservicemesh/deployments-k8s/issues/4271
> Fan-in-releasing Fix

- .github/workflows/release.yaml
https://github.com/networkservicemesh/deployments-k8s/issues/4776
> Improve Check Images job

- .github/workflows/release.yaml
https://github.com/networkservicemesh/deployments-k8s/issues/4777
> Fix Release action

- .github/workflows/ci.yaml
- .github/workflows/link-checker.yaml
https://github.com/networkservicemesh/deployments-k8s/issues/4775
> Skip link checker on Release

- .github/workflows/release.yaml
https://github.com/networkservicemesh/deployments-k8s/issues/4804
> Update refs to the latest tag on Release

- apps/forwarder-vpp/forwarder.yaml
- examples/features/select-forwarder/forwarder.yaml
Issue: https://github.com/networkservicemesh/integration-k8s-kind/issues/325
> Update forwarder yaml to use it with an external vpp

- examples/observability/jaeger-and-prometheus/README.md
> Improve example description

- examples/remotevlan/rvlanovs/README.md
- examples/remotevlan/rvlanovs/kustomization.yaml
- examples/remotevlan/rvlanvpp/README.md
- examples/remotevlan/rvlanvpp/kustomization.yaml
> Fix references in remote vlan examples

- apps/forwarder-vpp/forwarder.yaml
- examples/features/select-forwarder/forwarder.yaml
Issue: https://github.com/networkservicemesh/integration-k8s-kind/issues/325
> [qfix] Replace /var/run/vpp-ext with /var/run/vpp

- apps/nse-vl3-vpp/nse.yaml
Fixes https://github.com/networkservicemesh/integration-k8s-kind/pull/613
> qfix: Remove typo in nse-vl3-vpp deployment

- examples/features/dns/README.md
- external-images.yaml
According to: https://kubernetes.io/docs/tasks/administer-cluster/dns-debugging-resolution/
Closes: https://github.com/networkservicemesh/integration-k8s-kind/issues/604
> Update dnsutils image

- examples/features/policy-based-routing/README.md
- external-images.yaml
Closes: https://github.com/networkservicemesh/deployments-k8s/issues/5038
> Use nettools image instead of custom alpine_iproute2

- apps/forwarder-vpp/forwarder.yaml
- examples/features/select-forwarder/forwarder.yaml
> Mount shared vpp to an external folder

- examples/remotevlan/README.md
- examples/remotevlan/rvlanovs/README.md
- examples/remotevlan/rvlanovs/selector
- examples/remotevlan/rvlanvpp/README.md
- examples/remotevlan/rvlanvpp/selector
> Fix for interface name collision in RvlanSuiteSingle

- examples/features/mutually-aware-nses/config-file-nse-1.yaml
- examples/features/mutually-aware-nses/config-file-nse-2.yaml
- examples/features/policy-based-routing/README.md
- examples/features/policy-based-routing/config-file-nse.yaml
Closes: https://github.com/networkservicemesh/deployments-k8s/issues/5135
> Update policy based routing example

- examples/spire/agent-daemonset.yaml
- examples/spire/server-statefulset.yaml
- external-images.yaml
Issue: https://github.com/networkservicemesh/deployments-k8s/issues/5379
> Update spire version

- examples/spire/agent-daemonset.yaml
- examples/spire/server-statefulset.yaml
- external-images.yaml
Address CVE-2022-24675, CVE-2022-28327, CVE-2022-27536.
> bump: update spire from v1.2.2 to v1.2.3

- examples/heal/README.md
- examples/heal/dataplane-interrupt/README.md
- examples/heal/local-nse-death/README.md
> healing examples

- examples/features/scale-from-zero/pod-template.yaml
> [qfix] Add nodeName to pod template in scale-from-zero example

- examples/heal/vl3-nscs-death/kustomization.yaml
- examples/heal/vl3-nse-death/kustomization.yaml
> [qfix] Fix relative paths in vl3-heal tests

- Dockerfile
Signed-off-by: Ed Warnicke <hagbard@gmail.com>
> Add jq to --target shell

- examples/nsm+istio/README-KIND.md
- examples/nsm+istio/README.md
- examples/nsm+istio/nsm/cluster1/kustomization.yaml
- examples/nsm+istio/nsm/cluster2/kustomization.yaml
> add fixes for kind setup related to packet

- examples/heal/vl3-nse-death/README.md
> [qfix] vl3-heal-nse-death: fix NSE deletion

- Dockerfile.aks2gke
> add fixes into dockerfile aks2gke

- to-export.sh
- to-local.sh
Missed here - https://github.com/networkservicemesh/deployments-k8s/pull/6227
> [qfix] Fix to-export, to-local

- examples/features/vl3-basic/README.md
- examples/features/vl3-basic/kustomization.yaml
https://github.com/networkservicemesh/deployments-k8s/issues/6177
> Use urls for vl3-basic example

- examples/features/vl3-scale-from-zero/README.md
- examples/features/vl3-scale-from-zero/kustomization.yaml
https://github.com/networkservicemesh/deployments-k8s/issues/6177
> Use urls for vl3-scale-from-zero example

- examples/nsm_istio/README.md
- examples/nsm_istio/spire/README.md
Fixes error
```
Error from server (NotFound): error when deleting "./cluster2": namespaces "spire" not found
Error from server (NotFound): error when deleting "./cluster2": customresourcedefinitions.apiextensions.k8s.io "spiffeids.spiffeid.spiffe.io" not found
Error from server (NotFound): error when deleting "./cluster2": serviceaccounts "spire-agent" not found
Error from server (NotFound): error when deleting "./cluster2": serviceaccounts "spire-server" not found
Error from server (NotFound): error when deleting "./cluster2": clusterroles.rbac.authorization.k8s.io "k8s-workload-registrar-role" not found
Error from server (NotFound): error when deleting "./cluster2": clusterroles.rbac.authorization.k8s.io …
```
> fix issue with removing spire namepsace

- examples/nsm_istio/spire/README.md
> qfix: add spire wait ready to avoid potential nil bundle set

- .github/workflows/ci.yaml
https://github.com/networkservicemesh/deployments-k8s/issues/6645
> Filter for refcheck job that excludes new files

- examples/features/vl3-dns/README.md
> qfix: app label is wrong in vl3 dns example

- examples/floating_interdomain/spire/README.md
> Fix floating interdomain spire

- .github/workflows/automerge.yaml
> Add print-debug-info job to automerge workflow

- examples/features/vl3-basic/README.md
- examples/features/vl3-basic/kustomization.yaml
- examples/features/vl3-basic/nse-patch.yaml
- examples/features/vl3-basic/vl3-netsvc.yaml
- examples/features/vl3-dns/README.md
- examples/features/vl3-dns/nse-patch.yaml
- examples/features/vl3-dns/vl3-netsvc.yaml
Add netsvc config for vl3 networkservice for vl3-dns and vl3-basic examples
Signed-off-by: anastasia.malysheva <anastasia.malysheva@xored.com>
https://github.com/networkservicemesh/deployments-k8s/issues/6870
> Add networkService configs for vL3 examples

- examples/features/vl3-basic/README.md
- examples/features/vl3-basic/kustomization.yaml
- examples/features/vl3-dns/README.md
- examples/features/vl3-dns/kustomization.yaml
- examples/features/vl3-dns/nse-patch.yaml
> Fix vl3 network service usage

- examples/features/jaeger/opentelemetry/otel-collector.yaml
- examples/observability/jaeger-and-prometheus/jaeger/jaeger.yaml
- examples/observability/jaeger-and-prometheus/opentelemetry/otel-collector.yaml
- examples/observability/jaeger-and-prometheus/prometheus/prometheus.yaml
- external-images.yaml
> Use specific images version for observability

- examples/interdomain/nsm/README.md
> qfix: fix interdomain typo

- examples/features/annotated-namespace/README.md
Fix link to the file
Signed-off-by: anastasia.malysheva <anastasia.malysheva@xored.com>
> Fix annotated-namespace example

- examples/interdomain/nsm_kuma_universal_vl3/README.md
> Fix for falsely passing test

- apps/cluster-info/binding.yaml
- apps/cluster-info/cluster-info.yaml
- apps/cluster-info/configmap.yaml
- apps/cluster-info/kustomization.yaml
- apps/cluster-info/role.yaml
- apps/cluster-info/sa.yaml
- examples/floating_interdomain/clusters-configuration/cluster1/cluster-property.yaml
- examples/floating_interdomain/clusters-configuration/cluster1/kustomization.yaml
- examples/floating_interdomain/clusters-configuration/cluster1/patch-nsmgr-proxy.yaml
- examples/floating_interdomain/clusters-configuration/cluster2/cluster-property.yaml
- examples/floating_interdomain/clusters-configuration/cluster2/kustomization.yaml
- examples/floating_interdomain/clusters-configuration/cluster2/patch-nsmgr-proxy.yaml
- examples/floating_interdomain/usecases/FloatingVl3-scale-from-zero/cluster1/pod-template.yaml
- examples/floating_interdomain/usecases/FloatingVl3-scale-from-zero/cluster2/pod-template.yaml
Adds a simple example that checks cluster-info for single cluster.
The interdomain part will be applied right after merge of https://github.com/networkservicemesh/deployments-k8s/pull/7057
> feat: Add cluster-info example

- apps/nsc-vfio/nsc.yaml
- apps/nse-vfio/nse-configmap.yaml
- examples/use-cases/Kernel2Kernel&Vfio2Noop/README.md
- examples/use-cases/Kernel2Vxlan2Kernel&Vfio2Noop/README.md
- examples/use-cases/Vfio2Noop/README.md
This configuration was moved to Packet nodes setup
> Remove ulimit sriov config

- examples/interdomain/nsm_kuma_universal_vl3/README.md
> change to refs, fix ci error

- examples/observability/jaeger-and-prometheus/README.md
> Select forwarder properly in observability example

- .github/workflows/update-refs.yaml
- examples/floating_interdomain/clusters-configuration/cluster1/kustomization.yaml
- examples/floating_interdomain/clusters-configuration/cluster2/kustomization.yaml
- to-export.sh
- to-local.sh
We only need to update refs that belong to the `deployment-k8s` repository
https://github.com/networkservicemesh/integration-k8s-kind/pull/715
> Fix sed command to update refs correctly

- examples/floating_interdomain/clusters-configuration/cluster1/patch-nsmgr-proxy.yaml
- examples/floating_interdomain/clusters-configuration/cluster2/patch-nsmgr-proxy.yaml
- examples/floating_interdomain/usecases/FloatingVl3-scale-from-zero/cluster1/supplier-patch.yaml
- examples/floating_interdomain/usecases/FloatingVl3-scale-from-zero/cluster2/supplier-patch.yaml
> qfix: dont use clusterName label with clusterinfo on the cluster

- examples/interdomain/nsm_consul/README.md
- examples/interdomain/nsm_consul_vl3/README.md
> Fix port-forward typo

- examples/interdomain/nsm_consul/README.md
Motivation: https://github.com/networkservicemesh/integration-k8s-kind/actions/runs/3131341528/jobs/5082578365
> consul: replace brew with apt-get

- apps/nsc-vfio/nsc.yaml
- apps/nse-vfio/nse-configmap.yaml
- apps/nse-vfio/nse.yaml
- examples/multiforwarder/README.md
- examples/use-cases/Kernel2Kernel&Vfio2Noop/netsvc.yaml
- examples/use-cases/Kernel2Kernel_Vfio2Noop/README.md
- examples/use-cases/Kernel2Kernel_Vfio2Noop/kustomization.yaml
- examples/use-cases/Kernel2Kernel_Vfio2Noop/netsvc.yaml
- examples/use-cases/Kernel2Kernel_Vfio2Noop/patch-nsc.yaml
- examples/use-cases/Kernel2Kernel_Vfio2Noop/patch-nse.yaml
- examples/use-cases/Kernel2Vxlan2Kernel_Vfio2Noop/README.md
- examples/use-cases/Kernel2Vxlan2Kernel_Vfio2Noop/kustomization.yaml
- examples/use-cases/Kernel2Vxlan2Kernel_Vfio2Noop/netsvc.yaml
- examples/use-cases/Kernel2Vxlan2Kernel_Vfio2Noop/patch-nsc.yaml
- examples/use-cases/Kernel2Vxlan2Kernel_Vfio2Noop/patch-nse.yaml
- examples/use-cases/Vfio2Noop/README.md
- examples/use-cases/Vfio2Noop/kustomization.yaml
Closes: https://github.com/networkservicemesh/deployments-k8s/issues/7559
> Fix vfio examples

- examples/floating_interdomain/usecases/FloatingVl3/README.md
> qfix: remove unused steps from floating vl3 example

- examples/k8s_monolith/README.md
- examples/k8s_monolith/configuration/loadbalancer/README.md
- examples/k8s_monolith/external_nsc/README.md
- examples/k8s_monolith/external_nse/README.md
> Add more description for monolith examples

- examples/floating_interdomain/usecases/FloatingVl3/README.md
> qfix: floating interdomain vl3 ip-address

- examples/interdomain/spire/README.md
> Fix for typo about amount of clusters

- examples/floating_interdomain/dns/README.md
- examples/interdomain/dns/README.md
- examples/k8s_monolith/external_nsc/dns/README.md
- external-images.yaml
> dns: wrap exposed ipv6 ip in square brackets

- examples/interdomain/nsm_consul_vl3/README.md
- examples/interdomain/nsm_kuma_universal_vl3/README.md
Fix for unstable nsm_consul_vl3, nsm_kuma_vl3 tests
> Unstable Nsm_consul_vl3, nsm_kuma_vl3 test fix

- examples/features/annotated-namespace/client.yaml
https://github.com/networkservicemesh/deployments-k8s/issues/7676
> Change annotated-namespace to use deployment in client

- .github/workflows/update-dependent-repositories.yaml
https://github.com/networkservicemesh/deployments-k8s/actions/runs/3435481907/jobs/5727893795#step:10:5376
> Update go version in update-dependent-repositories workflow

- examples/interdomain/nsm_consul/README.md
> Set version for consul-k8s

- examples/use-cases/Kernel2RVlanMultiNS/README.md
Different applications connecting to the same NS and using the the same VLAN. These NSCs now can run on the same node.
The test script with multiple network services and and k8s namespaces was modified.
A remote-vlan-nse type NSE provides two NS defining the same VLAN ID. The NSC connecting to these NSs are collocated on the same host.
networkservicemesh/deployments-k8s/issues/7687
> Add test case to vlan break-trough

- examples/remotevlan/README.md
- examples/remotevlan/netsvc.yaml
- examples/remotevlan/patch-nse.yaml
- examples/use-cases/Kernel2RVlanBreakout/.gitignore
- examples/use-cases/Kernel2RVlanBreakout/README.md
- examples/use-cases/Kernel2RVlanBreakout/first-iperf-s.yaml
- examples/use-cases/Kernel2RVlanBreakout/kustomization.yaml
- examples/use-cases/Kernel2RVlanInternal/.gitignore
- examples/use-cases/Kernel2RVlanInternal/README.md
- examples/use-cases/Kernel2RVlanInternal/first-iperf-s.yaml
- examples/use-cases/Kernel2RVlanInternal/kustomization.yaml
- examples/use-cases/Kernel2RVlanInternal/netsvc.yaml
- examples/use-cases/Kernel2RVlanMultiNS/.gitignore
- examples/use-cases/Kernel2RVlanMultiNS/README.md
- examples/use-cases/Kernel2RVlanMultiNS/client.yaml
- examples/use-cases/Kernel2RVlanMultiNS/ns-1/first-client.yaml
- examples/use-cases/Kernel2RVlanMultiNS/ns-1/kustomization.yaml
- examples/use-cases/Kernel2RVlanMultiNS/ns-1/netsvc.yaml
- examples/use-cases/Kernel2RVlanMultiNS/ns-1/patch-nse.yaml
- examples/use-cases/Kernel2RVlanMultiNS/ns-2/kustomization.yaml
- examples/use-cases/Kernel2RVlanMultiNS/ns-2/netsvc.yaml
- examples/use-cases/Kernel2RVlanMultiNS/ns-2/patch-nse.yaml
- examples/use-cases/Kernel2RVlanMultiNS/ns-2/second-client.yaml
- examples/use-cases/Kernel2RVlanMultiNS/ns-2/third-client.yaml
> rvlan: registering a NetworkService separately from an endpoint

- examples/features/vl3-basic/README.md
- examples/features/vl3-dns/README.md
- examples/features/vl3-scale-from-zero/README.md
- examples/heal/vl3-nscs-death/README.md
- examples/heal/vl3-nse-death/README.md
- examples/k8s_monolith/external_nse/usecases/Kernel2Wireguard2Kernel/README.md
> Reduce ping count and interval parameters in for loops

- .github/workflows/release.yaml
See - https://github.com/networkservicemesh/deployments-k8s/blob/v1.7.0-rc.1/examples/multicluster/clusters-configuration/cluster1/kustomization.yaml#L8
> Fix 'update-refs' job for release

- apps/nsc-vfio/nsc.yaml
- apps/nse-vfio/nse.yaml
- examples/use-cases/Kernel2Ethernet2Kernel_Vfio2Noop/README.md
- examples/use-cases/Kernel2Ethernet2Kernel_Vfio2Noop/kustomization.yaml
- examples/use-cases/Kernel2Ethernet2Kernel_Vfio2Noop/netsvc.yaml
- examples/use-cases/Kernel2Ethernet2Kernel_Vfio2Noop/patch-nsc-vfio.yaml
- examples/use-cases/Kernel2Ethernet2Kernel_Vfio2Noop/patch-nse-vfio.yaml
- examples/use-cases/Kernel2Kernel_Vfio2Noop/README.md
- examples/use-cases/Kernel2Kernel_Vfio2Noop/kustomization.yaml
- examples/use-cases/Kernel2Kernel_Vfio2Noop/netsvc.yaml
- examples/use-cases/Kernel2Kernel_Vfio2Noop/patch-nsc-vfio.yaml
- examples/use-cases/Kernel2Kernel_Vfio2Noop/patch-nse-vfio.yaml
- examples/use-cases/Vfio2Noop/README.md
- examples/use-cases/Vfio2Noop/kustomization.yaml
- examples/use-cases/Vfio2Noop/netsvc.yaml
- examples/use-cases/Vfio2Noop/patch-nsc-vfio.yaml
- examples/use-cases/Vfio2Noop/patch-nse-vfio.yaml
> vfio: register the service separately

- examples/interdomain/nsm_consul/README.md
- examples/interdomain/nsm_consul/client/dashboard.yaml
- examples/interdomain/nsm_consul/kind-cluster-config.yaml
- examples/interdomain/nsm_consul/networkservice.yaml
- examples/interdomain/nsm_consul/nse-auto-scale-client/iptables-map.yaml
- examples/interdomain/nsm_consul/nse-auto-scale-client/kustomization.yaml
- examples/interdomain/nsm_consul/nse-auto-scale-client/pod-template.yaml
- examples/interdomain/nsm_consul/nse-auto-scale-client/supplier.yaml
- examples/interdomain/nsm_consul/nse-auto-scale-server/iptables-map.yaml
- examples/interdomain/nsm_consul/nse-auto-scale-server/kustomization.yaml
- examples/interdomain/nsm_consul/nse-auto-scale-server/patch-supplier.yaml
- examples/interdomain/nsm_consul/nse-auto-scale-server/pod-template.yaml
- examples/interdomain/nsm_consul/nse-auto-scale/iptables-map.yaml
- examples/interdomain/nsm_consul/server/counting.yaml
- examples/interdomain/nsm_consul/server/counting_nsm.yaml
- examples/interdomain/nsm_consul/server/counting_service.yaml
Closes: https://github.com/networkservicemesh/deployments-k8s/issues/7896
> Fix consul iptables

- .github/workflows/release.yaml
Incident https://github.com/networkservicemesh/deployments-k8s/actions/runs/3685237395/jobs/6235993864
> qfix: Release action is not working

- .github/workflows/release.yaml
> qfix: Release action is not working for release/v1.7.0-rc.2

- examples/interdomain/nsm_consul/README.md
> [qfix]: Fix consul refs

- apps/nse-kernel/nse.yaml
- examples/features/exclude-prefixes-client/nse-kernel-1.yaml
- examples/features/exclude-prefixes-client/nse-kernel-2.yaml
- examples/features/mutually-aware-nses/nse-1.yaml
- examples/features/mutually-aware-nses/nse-2.yaml
- examples/features/scale-from-zero/pod-template.yaml
- examples/multicluster/usecases/floating_Kernel2Wireguard2Kernel/cluster2/nse.yaml
Signed-off-by: NSMBot <nsmbot@networkservicmesh.io>
> Update docker images to the latest tag v1.7.0

- apps/forwarder-vpp/forwarder.yaml
- apps/nsmgr/nsmgr.yaml
- apps/registry-k8s/registry-k8s.yaml
https://github.com/networkservicemesh/deployments-k8s/issues/5494
> Update limits for nsmgr, forwarder-vpp and registry-k8s

- examples/ipsec_mechanism/kustomization.yaml
- examples/ipsec_mechanism/nsm-system-namespace.yaml
- examples/k8s_monolith/configuration/cluster/kustomization.yaml
- examples/k8s_monolith/configuration/cluster/nsm-system-namespace.yaml
- examples/memory/kustomization.yaml
- examples/memory/nsm-system-namespace.yaml
- examples/multicluster/clusters-configuration/cluster1/kustomization.yaml
- examples/multicluster/clusters-configuration/cluster1/nsm-system-namespace.yaml
- examples/multicluster/clusters-configuration/cluster2/kustomization.yaml
- examples/multicluster/clusters-configuration/cluster2/nsm-system-namespace.yaml
- examples/multicluster/clusters-configuration/cluster3/kustomization.yaml
- examples/multicluster/clusters-configuration/cluster3/nsm-system-namespace.yaml
- examples/multiforwarder/kustomization.yaml
- examples/multiforwarder/nsm-system-namespace.yaml
- examples/ovs/kustomization.yaml
- examples/ovs/nsm-system-namespace.yaml
- examples/remotevlan/kustomization.yaml
- examples/remotevlan/nsm-system-namespace.yaml
- examples/sriov/kustomization.yaml
- examples/sriov/nsm-system-namespace.yaml
Fix relative namespace resource
https://github.com/networkservicemesh/integration-k8s-kind/actions/runs/4037867631/jobs/6941461037
> Fix relative resource

- examples/interdomain/nsm_consul/README.md
- examples/interdomain/nsm_istio/README.md
https://github.com/networkservicemesh/integration-k8s-kind/issues/777
> Fix consul test

- .github/workflows/pr-for-release.yaml
Fix quotes
https://github.com/networkservicemesh/integration-k8s-packet/issues/312
> Fix quotes

- examples/features/nse-composition/README.md
https://github.com/networkservicemesh/integration-k8s-aks/pull/266
> Fix alpine wait timeout in nse-composition

- examples/multicluster/README.md
- examples/multicluster/loadbalancer/README.md
> Fix some relative paths in examples/multicluster folder

- examples/heal/README.md
- examples/heal/spire-agent-restart/README.md
- examples/heal/spire-agent-restart/kustomization.yaml
- examples/heal/spire-agent-restart/netsvc.yaml
- examples/heal/spire-agent-restart/patch-nsc.yaml
- examples/heal/spire-agent-restart/patch-nse.yaml
- examples/heal/spire-server-agent-restart/README.md
- examples/heal/spire-server-agent-restart/kustomization.yaml
- examples/heal/spire-server-agent-restart/netsvc.yaml
- examples/heal/spire-server-agent-restart/patch-nsc.yaml
- examples/heal/spire-server-agent-restart/patch-nse.yaml
- examples/heal/spire-server-restart/README.md
- examples/heal/spire-server-restart/kustomization.yaml
- examples/heal/spire-server-restart/netsvc.yaml
- examples/heal/spire-server-restart/patch-nsc.yaml
- examples/heal/spire-server-restart/patch-nse.yaml
- examples/heal/spire-upgrade/README.md
- examples/heal/spire-upgrade/kustomization.yaml
- examples/heal/spire-upgrade/netsvc.yaml
- examples/heal/spire-upgrade/patch-nsc.yaml
- examples/heal/spire-upgrade/patch-nse.yaml
Signed-off-by: Szilard Vincze <szilard.vincze@est.tech>
Four test cases added to healing examples:
1) SPIRE agents restart
2) SPIRE server restart
3) Both SPIRE server and agents restart
4) SPIRE upgrade-like deployment removal and re-installation
-
> Examples with different SPIRE restarts

- examples/heal/spire-upgrade/README.md
In the meantime the spire manifests were split into single and multi cluster, thus I needed to do a bit of a rebase.
> Fix for spire upgrade in heal suite

- examples/use-cases/SriovKernel2Noop/patch-nsc.yaml
This reverts commit 9eec76e6d104b58a474ae299d3b1e8108b405a64.
https://github.com/networkservicemesh/integration-k8s-packet/issues/320
> Revert "Temporarily disable livenesscheck for SriovKernel2Noop (#8788)"

- external-images.yaml
external-images.yaml updated with the images needed for SPIRE 1.6.1
[Fix Spire #8986](https://github.com/networkservicemesh/deployments-k8s/pull/8986)
> External images updated

- examples/features/nse-composition/config-file.yaml
- examples/features/nse-composition/nse-firewall/config-patch.yaml
> Remove `vppagent` prefix from `nse-composition` example

- apps/registry-memory/registry-memory.yaml
> Update docker images to the latest tag v1.9.0-rc.1

- apps/admission-webhook-k8s/admission-webhook.yaml
> [qfix] Update refs for admission-webhook

- examples/features/annotated-namespace/README.md
Add check for client ID generation by admission-webhook
https://github.com/networkservicemesh/deployments-k8s/issues/9170
> Add check for client ID generation

- .github/workflows/pr-for-updates.yaml
Recently we see that our CI is sometimes failing to create pull requests.
In the repo of the action we use there is a test branch that is supposed to fix it.
In this PR I update our CI to use this branch.
https://github.com/networkservicemesh/.github/issues/27
> Update action version in pr-for-updates.yaml

- .github/workflows/pr-for-updates.yaml
Partially revert this:
- https://github.com/networkservicemesh/deployments-k8s/pull/9214
> Change github token in CI workflow

- apps/csi-driver/csi-driver.yaml
- apps/csi-driver/kustomization.yaml
- examples/features/webhook/README.md
- examples/pss/README.md
- examples/pss/nsm-system/kustomization.yaml
- examples/pss/nsm-system/nsm-system-namespace.yaml
- examples/pss/nsm-system/patch-admission-webhook-k8s.yaml
- examples/pss/nsm-system/patch-forwarder-vpp.yaml
- examples/pss/nsm-system/patch-nsmgr.yaml
- examples/pss/nsm-system/patch-registry-k8s.yaml
- examples/pss/use-cases/nginx/README.md
- examples/pss/use-cases/nginx/client.yaml
- examples/pss/use-cases/nginx/kustomization.yaml
- examples/pss/use-cases/nginx/netsvc.yaml
- examples/pss/use-cases/nginx/ns-nginx.yaml
- examples/pss/use-cases/nginx/patch-nse.yaml
- examples/spire/single_cluster_csi/README.md
- examples/spire/single_cluster_csi/kustomization.yaml
- examples/spire/single_cluster_csi/patch-agent-daemonset.yaml
- examples/spire/single_cluster_csi/spiffe-csi-driver.yaml
- external-images.yaml
This PR adds PSS policy example
https://kubernetes.io/docs/concepts/security/pod-security-standards/
Issue: https://github.com/networkservicemesh/deployments-k8s/issues/9218
> Add k8s PSS policy example 

- .github/workflows/release.yaml
- .github/workflows/update-dependent-repositories.yaml
https://github.com/networkservicemesh/deployments-k8s/issues/9216
> Update to go 1.20

- examples/observability/jaeger-and-prometheus/README.md
> Fix Jaeger and Prometheus Observability example

- examples/features/exclude-prefixes/README.md
- examples/features/exclude-prefixes/configmap/exclude-prefixes-config-map.yaml
- examples/features/exclude-prefixes/exclude-prefixes-config-map.yaml
- examples/features/exclude-prefixes/patch-nse.yaml
> fix exclude-prefixes test

- .github/ISSUE_TEMPLATE/question.md
Template **.github/ISSUE_TEMPLATE/question.md** has a typo
> Fix typo in .github/ISSUE_TEMPLATE/question.md

- examples/heal/remote-nse-death-ip/README.md
- examples/heal/remote-nse-death/README.md
> [qfix] Fix some typos

- examples/interdomain/dns/README.md
- examples/interdomain/nsm/README.md
Currently we test 2-cluster interdomain setup only in Kind.
When I tried to run automated 2-cluster tests using public clouds, I found a few issues.
> Fix external DNS for interdomain

- examples/multicluster_heal/interdomain-registry-death/cluster2/kustomization.yaml
https://github.com/networkservicemesh/integration-k8s-kind/actions/runs/6118266889/job/16626076684?pr=878
> [qfix] Fix links in kustomization files for interdomain-registry-death example

- examples/features/vl3-scale-from-zero/client.yaml
- examples/features/vl3-scale-from-zero/kustomization.yaml
- examples/features/vl3-scale-from-zero/pod-template.yaml
- examples/features/vl3-scale-from-zero/supplier-patch.yaml
- examples/features/vl3-scale-from-zero/vl3-netsvc.yaml
- examples/features/vl3-scale-from-zero/vl3-scale-from-zero.yaml
- examples/multicluster/usecases/floating_vl3-scale-from-zero/cluster1/pod-template.yaml
- examples/multicluster/usecases/floating_vl3-scale-from-zero/cluster2/pod-template.yaml
- examples/multicluster/usecases/floating_vl3-scale-from-zero/cluster3/netsvc.yaml
Blocked by https://github.com/networkservicemesh/cmd-nse-vl3-vpp/pull/231
Fixes https://github.com/networkservicemesh/integration-k8s-kind/pull/883
> Fix vl3 scale from zero test

- .github/workflows/release.yaml
https://github.com/networkservicemesh/deployments-k8s/issues/9726
> Change log level to INFO for releases

- .github/workflows/release.yaml
> release: fix tag retrieving

- .github/workflows/release.yaml
Closes: https://github.com/networkservicemesh/deployments-k8s/issues/10093
> Fix release workflow typo

- .github/workflows/release.yaml
Closes https://github.com/networkservicemesh/.github/issues/49
https://github.com/networkservicemesh/.github/issues/49
> feat: Add docker images CVE scanner

- .github/workflows/check-cves.yaml
https://github.com/networkservicemesh/deployments-k8s/issues/10500
> Add a workflow for checking CVEs weekly

- .github/workflows/check-cves.yaml
Should fix a broken CVEs cronjob.
https://github.com/networkservicemesh/deployments-k8s/actions/runs/6998905397/job/19037569913
> [qfix] Fix envs names in CVEs cronjob

- apps/admission-webhook-k8s/mutating-webhook-config.yaml
- examples/afxdp/README.md
- examples/basic/README.md
- examples/features/jaeger/README.md
- examples/heal/local-nsm-system-restart/README.md
- examples/heal/remote-nsm-system-restart-memif-ip/README.md
- examples/interdomain/nsm/README.md
- examples/ipsec_mechanism/README.md
- examples/k8s_monolith/external_nsc/README.md
- examples/k8s_monolith/external_nse/README.md
- examples/memory/README.md
- examples/multicluster/README.md
- examples/multicluster_heal/floating-nsm-system-death/README.md
- examples/multiforwarder/README.md
- examples/multiforwarder_vlantag/README.md
- examples/observability/jaeger-and-prometheus/README.md
- examples/ovs/README.md
- examples/pss/README.md
- examples/remotevlan_ovs/README.md
- examples/remotevlan_vpp/README.md
- examples/spire/cluster1/README.md
- examples/spire/cluster2/README.md
- examples/spire/cluster3/README.md
- examples/sriov/README.md
- examples/sriov_vlantag/README.md
Fix interdomain tests failures
https://github.com/networkservicemesh/cmd-admission-webhook-k8s/issues/291
> Fix interdomain tests failures

- apps/admission-webhook-k8s/mutating-webhook-config.yaml
Fix TestRunRvlanOVSSuite tests failures
https://github.com/networkservicemesh/cmd-admission-webhook-k8s/issues/291
> Fix TestRunRvlanOVSSuite tests failures

- .github/workflows/check-cves.yaml
Use real secrets for `docker login`
> [qfix] Fix docker login in CVEs workflow

- .github/workflows/pr-for-release.yaml
- .github/workflows/pr-for-updates.yaml
https://github.com/networkservicemesh/deployments-k8s/actions/runs/7164626599/job/19509710566
> Update image version for pull request actions

- .github/workflows/check-cves.yaml
Scan images for CVEs everyday to fix all CVEs quickly
https://github.com/networkservicemesh/deployments-k8s/issues/10770
> [qfix] Scan for CVEs everyday

- .github/workflows/check-cves.yaml
Disable removing previous CVEs analyses to keep the history of fixed CVEs
> [qfix] Delete removing previous CVEs analyses

- examples/features/scaled-registry/README.md
Fix the check of unregistered NSE
https://github.com/networkservicemesh/integration-k8s-kind/actions/runs/7273024925/job/19816208286?pr=934
> [qfix] Fix Scaled Registry Test

- examples/features/scaled-registry/README.md
https://github.com/networkservicemesh/integration-k8s-kind/pull/936
> [qfix] Find NSE by its full name in Scaled Registry Test

- apps/dashboard/dashboard-backend-service.yaml
- apps/dashboard/dashboard-pod.yaml
- apps/dashboard/dashboard-ui-service.yaml
- apps/dashboard/kustomization.yaml
- examples/observability/README.md
- examples/observability/dashboard/README.md
Add NSM Dashboard deployment files.
> Add NSM Dashboard deployment files.

- .github/workflows/check-cves.yaml
https://github.com/networkservicemesh/deployments-k8s/issues/10810
> Merge CVEs

- examples/features/change-nse-dynamically/README.md
> qfix: Example: NSC changes NSE on Network Service updated doesnt work on CI

- examples/features/scaled-registry/README.md
> scaled registry: wait for registry-k8s to be deleted

- examples/features/change-nse-dynamically/README.md
- examples/features/change-nse-dynamically/blue-nse.yaml
- examples/features/change-nse-dynamically/green-netsvc.yaml
- examples/features/change-nse-dynamically/green-nse.yaml
> Fix Test_Change_NSE_Dynamically typos

- .github/workflows/check-failed-workflows.yaml
- .github/workflows/pr-for-updates.yaml
Add new workflow to check failed workflows that update cmd-apps versions. It reruns them if finds any.
> Use cronjob to search for failed workflows

- .github/workflows/check-failed-workflows.yaml
https://github.com/networkservicemesh/deployments-k8s/actions/runs/7454770604
> [qfix] Fix Check Failed Workflows Action

- .github/workflows/update-dependent-repositories.yaml
https://github.com/networkservicemesh/integration-tests/pull/3374
> qfix: deployments-k8s should update only generated files for integration-tests repo

- examples/features/vl3-ipv6/README.md
> GKE: Fix vl3 ipv6 example failures.

- .github/workflows/release.yaml
- examples/features/policy-based-routing/client.yaml
- examples/features/vl3-lb/finance-client.yaml
- examples/features/vl3-lb/finance-lb-patch.yaml
- examples/features/vl3-lb/finance-server.yaml
- examples/features/webhook/client.yaml
- examples/interdomain/usecases/nsm_istio/greeting/server.yaml
- examples/pss/use-cases/nginx/client.yaml
- examples/spire/base/agent-daemonset.yaml
- external-images.yaml
Updated images can work with both amd64 and arm64
Issue: https://github.com/networkservicemesh/integration-tests/issues/3390
> Replace images with ones that support ARM64

- .github/workflows/update-refs.yaml
> don't allow NSMBot to commit refs changes as an anonymous user

- .github/workflows/release.yaml
https://github.com/networkservicemesh/.github/issues/58
> Use a reusable workflow in create-release job

- .github/workflows/update-refs.yaml
> Remove `automerge is completed` trigger from `Update References` action

- examples/sriov/README.md
> Fix links in `sriov` suite

- .github/workflows/update-refs.yaml
> [qfix] Use `nsmbot` instead `NSMBot`

- .github/workflows/check-release-branches.yaml
https://github.com/networkservicemesh/deployments-k8s/actions/runs/9086795695
> Fix trigger in `check-release-branches` workflow

- examples/interdomain/usecases/floating_vl3-scale-from-zero/README.md
https://github.com/networkservicemesh/deployments-k8s/actions/runs/9082332443/job/24958409607?pr=11961
> Remove a broken link

- .github/workflows/check-release-branches.yaml
https://github.com/networkservicemesh/deployments-k8s/actions/runs/9290757417/job/25567719224#step:4:3
> fix `Set envs` step in `check-release-branches` workflow

- examples/features/annotated-namespace/README.md
> Don't depend on logs in the tests

- .github/workflows/check-tag.yaml
- apps/forwarder-vpp/forwarder.yaml
- apps/nsmgr/nsmgr.yaml
- apps/registry-k8s/registry-k8s.yaml
Added NSM_PPROF_ENABLED and NSM_PPROF_PORT envs to config for profiling.
https://github.com/networkservicemesh/deployments-k8s/issues/12045
> Add NSM_PPROF_ENABLED and NSM_PPROF_PORT to configs

- .github/workflows/release.yaml
- .github/workflows/update-dependent-repositories.yaml
Issue: https://github.com/networkservicemesh/deployments-k8s/issues/12294
> Update go to 1.23

- .github/workflows/ci.yaml
https://github.com/networkservicemesh/deployments-k8s/issues/12172
> Add a YAML linter for k8s yaml files

- .github/workflows/link-checker.yaml
Add an exemption for cncf slack channel link to the link checker temporary.
This is a workflow fix.
> Quick fix for link checker workflow

- .github/workflows/automerge.yaml
This pull request modifies the automerge workflow to only proceed with merging, if the pull request was created by nsmbot.
> Modify automerge workflow to only accept pull requests from nsmbot

- .github/workflows/automerge.yaml
- .github/workflows/update-dependent-repositories.yaml
- .github/workflows/update-refs.yaml
This PR updates the automerge workflow to also allow pull requests opened by Dependabot.
> Adjust accepted actors of automerge workflow

- .github/dependabot.yml
- .github/workflows/automerge.yaml
- .github/workflows/update-dependent-repositories.yaml
- .github/workflows/update-refs.yaml
This PR introduces a prefix for commits and pull requests created by Dependabot for uplifting github actions.
> Introduce prefix for commits created by dependabot

- examples/interdomain/three_cluster_configuration/loadbalancer/README.md
- examples/interdomain/two_cluster_configuration/dns/README.md
- examples/interdomain/two_cluster_configuration/loadbalancer/README.md
- examples/k8s_monolith/configuration/loadbalancer/README.md
MetalLB uplifted from 0.12.1 to 0.15.2 in the configuration.
> MetalLB uplift

- examples/spire/cluster1/service-patch.yaml
- examples/spire/cluster2/service-patch.yaml
- examples/spire/cluster3/service-patch.yaml
Fixed the issue with federation port (#12543 ).
Thanks to @anselmobattisti for reporting it.
#12543
> Fix for #12543

- examples/spire/base/server-statefulset.yaml
- examples/spire/cluster1/spire-controller-manager-config.yaml
- examples/spire/cluster2/spire-controller-manager-config.yaml
- examples/spire/cluster3/spire-controller-manager-config.yaml
- examples/spire/single_cluster/spire-controller-manager-config.yaml
Readiness and liveness probes of SCM activated in spire-server STS.
> SCM probes activated
